/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './header.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../auth/auth.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/router/src/directives/router_link';
import * as import12 from '@angular/router/src/router';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/common/src/location/location_strategy';
import * as import15 from '@angular/core/src/security';
var renderType_HeaderComponent_Host:import0.RenderComponentType = (null as any);
class _View_HeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import3.HeaderComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-header',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import3.HeaderComponent(this.parentInjector.get(import8.AuthService));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeaderComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeaderComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HeaderComponent_Host === (null as any))) { (renderType_HeaderComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_HeaderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeaderComponentNgFactory:import10.ComponentFactory<import3.HeaderComponent> = new import10.ComponentFactory<import3.HeaderComponent>('app-header',viewFactory_HeaderComponent_Host0,import3.HeaderComponent);
const styles_HeaderComponent:any[] = ['a#logout[_ngcontent-%COMP%]:hover { cursor: pointer; }'];
var renderType_HeaderComponent:import0.RenderComponentType = (null as any);
class _View_HeaderComponent0 extends import1.AppView<import3.HeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _RouterLinkWithHref_19_3:import11.RouterLinkWithHref;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _el_47:any;
  _RouterLinkWithHref_47_3:import11.RouterLinkWithHref;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _el_51:any;
  _RouterLinkWithHref_51_3:import11.RouterLinkWithHref;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _el_80:any;
  _el_81:any;
  _RouterLinkWithHref_81_3:import11.RouterLinkWithHref;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  _el_87:any;
  _RouterLinkWithHref_87_3:import11.RouterLinkWithHref;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _el_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _el_102:any;
  _text_103:any;
  _el_104:any;
  _el_105:any;
  _RouterLinkWithHref_105_3:import11.RouterLinkWithHref;
  _text_106:any;
  _text_107:any;
  _el_108:any;
  _el_109:any;
  _RouterLinkWithHref_109_3:import11.RouterLinkWithHref;
  _text_110:any;
  _text_111:any;
  _el_112:any;
  _text_113:any;
  _el_114:any;
  _el_115:any;
  _el_116:any;
  _text_117:any;
  _text_118:any;
  _text_119:any;
  _text_120:any;
  _text_121:any;
  _text_122:any;
  _text_123:any;
  _text_124:any;
  _el_125:any;
  _el_126:any;
  _el_127:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent0,renderType_HeaderComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'nav',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','navbar navbar-inverse navbar-fixed-top');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','container-fluid');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','navbar-header');
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_7,'class','navbar-toggle collapsed');
    this.renderer.setElementAttribute(this._el_7,'data-target','#bs-example-navbar-collapse-1');
    this.renderer.setElementAttribute(this._el_7,'data-toggle','collapse');
    this.renderer.setElementAttribute(this._el_7,'type','button');
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','sr-only');
    this._text_10 = this.renderer.createText(this._el_9,'Toggle navigation',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','icon-bar');
    this._text_13 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','icon-bar');
    this._text_15 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','icon-bar');
    this._text_17 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_5,'a',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','navbar-brand');
    this.renderer.setElementAttribute(this._el_19,'routerLink','/');
    this._RouterLinkWithHref_19_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_20 = this.renderer.createText(this._el_19,'FinTech',(null as any));
    this._text_21 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','collapse navbar-collapse');
    this.renderer.setElementAttribute(this._el_24,'id','bs-example-navbar-collapse-1');
    this._text_25 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','nav navbar-nav');
    this._text_27 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'li',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','active');
    this._el_29 = this.renderer.createElement(this._el_28,'a',(null as any));
    this.renderer.setElementAttribute(this._el_29,'href','#');
    this._text_30 = this.renderer.createText(this._el_29,'Link ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'span',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','sr-only');
    this._text_32 = this.renderer.createText(this._el_31,'(current)',(null as any));
    this._text_33 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_26,'li',(null as any));
    this._el_35 = this.renderer.createElement(this._el_34,'a',(null as any));
    this.renderer.setElementAttribute(this._el_35,'href','#');
    this._text_36 = this.renderer.createText(this._el_35,'Link',(null as any));
    this._text_37 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_26,'li',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','dropdown');
    this._text_39 = this.renderer.createText(this._el_38,'\n          ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'a',(null as any));
    this.renderer.setElementAttribute(this._el_40,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_40,'aria-haspopup','true');
    this.renderer.setElementAttribute(this._el_40,'class','dropdown-toggle');
    this.renderer.setElementAttribute(this._el_40,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_40,'href','#');
    this.renderer.setElementAttribute(this._el_40,'role','button');
    this._text_41 = this.renderer.createText(this._el_40,'Members ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_40,'span',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','caret');
    this._text_43 = this.renderer.createText(this._el_38,'\n          ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_38,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','dropdown-menu');
    this._text_45 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'li',(null as any));
    this._el_47 = this.renderer.createElement(this._el_46,'a',(null as any));
    this.renderer.setElementAttribute(this._el_47,'routerLink','/member/new');
    this._RouterLinkWithHref_47_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_48 = this.renderer.createText(this._el_47,'Add New',(null as any));
    this._text_49 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_44,'li',(null as any));
    this._el_51 = this.renderer.createElement(this._el_50,'a',(null as any));
    this.renderer.setElementAttribute(this._el_51,'routerLink','/member/list');
    this._RouterLinkWithHref_51_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_52 = this.renderer.createText(this._el_51,'Find',(null as any));
    this._text_53 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_44,'li',(null as any));
    this._el_55 = this.renderer.createElement(this._el_54,'a',(null as any));
    this.renderer.setElementAttribute(this._el_55,'href','#');
    this._text_56 = this.renderer.createText(this._el_55,'Something else here',(null as any));
    this._text_57 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_44,'li',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','divider');
    this.renderer.setElementAttribute(this._el_58,'role','separator');
    this._text_59 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_44,'li',(null as any));
    this._el_61 = this.renderer.createElement(this._el_60,'a',(null as any));
    this.renderer.setElementAttribute(this._el_61,'href','#');
    this._text_62 = this.renderer.createText(this._el_61,'Separated link',(null as any));
    this._text_63 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_44,'li',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','divider');
    this.renderer.setElementAttribute(this._el_64,'role','separator');
    this._text_65 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_44,'li',(null as any));
    this._el_67 = this.renderer.createElement(this._el_66,'a',(null as any));
    this.renderer.setElementAttribute(this._el_67,'href','#');
    this._text_68 = this.renderer.createText(this._el_67,'One more separated link',(null as any));
    this._text_69 = this.renderer.createText(this._el_44,'\n          ',(null as any));
    this._text_70 = this.renderer.createText(this._el_38,'\n        ',(null as any));
    this._text_71 = this.renderer.createText(this._el_26,'\n\n        ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_26,'li',(null as any));
    this.renderer.setElementAttribute(this._el_72,'class','dropdown');
    this._text_73 = this.renderer.createText(this._el_72,'\n          ',(null as any));
    this._el_74 = this.renderer.createElement(this._el_72,'a',(null as any));
    this.renderer.setElementAttribute(this._el_74,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_74,'aria-haspopup','true');
    this.renderer.setElementAttribute(this._el_74,'class','dropdown-toggle');
    this.renderer.setElementAttribute(this._el_74,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_74,'href','#');
    this.renderer.setElementAttribute(this._el_74,'role','button');
    this._text_75 = this.renderer.createText(this._el_74,'Schemes ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_74,'span',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','caret');
    this._text_77 = this.renderer.createText(this._el_72,'\n          ',(null as any));
    this._el_78 = this.renderer.createElement(this._el_72,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_78,'class','dropdown-menu');
    this._text_79 = this.renderer.createText(this._el_78,'\n            ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_78,'li',(null as any));
    this._el_81 = this.renderer.createElement(this._el_80,'a',(null as any));
    this.renderer.setElementAttribute(this._el_81,'routerLink','/scheme/new');
    this._RouterLinkWithHref_81_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_82 = this.renderer.createText(this._el_81,'Create New Scheme',(null as any));
    this._text_83 = this.renderer.createText(this._el_78,'\n            ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_78,'li',(null as any));
    this.renderer.setElementAttribute(this._el_84,'class','divider');
    this.renderer.setElementAttribute(this._el_84,'role','separator');
    this._text_85 = this.renderer.createText(this._el_78,'\n            ',(null as any));
    this._el_86 = this.renderer.createElement(this._el_78,'li',(null as any));
    this._el_87 = this.renderer.createElement(this._el_86,'a',(null as any));
    this.renderer.setElementAttribute(this._el_87,'routerLink','/plan/new');
    this._RouterLinkWithHref_87_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_88 = this.renderer.createText(this._el_87,'Add Plans To Scheme',(null as any));
    this._text_89 = this.renderer.createText(this._el_78,'\n          ',(null as any));
    this._text_90 = this.renderer.createText(this._el_72,'\n        ',(null as any));
    this._text_91 = this.renderer.createText(this._el_26,'\n\n      ',(null as any));
    this._text_92 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._text_93 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._el_94 = this.renderer.createElement(this._el_24,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_94,'class','nav navbar-nav navbar-right');
    this._text_95 = this.renderer.createText(this._el_94,'\n        ',(null as any));
    this._el_96 = this.renderer.createElement(this._el_94,'li',(null as any));
    this.renderer.setElementAttribute(this._el_96,'class','dropdown');
    this._text_97 = this.renderer.createText(this._el_96,'\n          ',(null as any));
    this._el_98 = this.renderer.createElement(this._el_96,'a',(null as any));
    this.renderer.setElementAttribute(this._el_98,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_98,'aria-haspopup','true');
    this.renderer.setElementAttribute(this._el_98,'class','dropdown-toggle');
    this.renderer.setElementAttribute(this._el_98,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_98,'href','#');
    this.renderer.setElementAttribute(this._el_98,'role','button');
    this._text_99 = this.renderer.createText(this._el_98,'',(null as any));
    this._el_100 = this.renderer.createElement(this._el_98,'span',(null as any));
    this.renderer.setElementAttribute(this._el_100,'class','caret');
    this._text_101 = this.renderer.createText(this._el_96,'\n          ',(null as any));
    this._el_102 = this.renderer.createElement(this._el_96,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_102,'class','dropdown-menu');
    this._text_103 = this.renderer.createText(this._el_102,'\n            ',(null as any));
    this._el_104 = this.renderer.createElement(this._el_102,'li',(null as any));
    this._el_105 = this.renderer.createElement(this._el_104,'a',(null as any));
    this.renderer.setElementAttribute(this._el_105,'routerLink','/edit/profile');
    this._RouterLinkWithHref_105_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_106 = this.renderer.createText(this._el_105,'Edit',(null as any));
    this._text_107 = this.renderer.createText(this._el_102,'\n            ',(null as any));
    this._el_108 = this.renderer.createElement(this._el_102,'li',(null as any));
    this._el_109 = this.renderer.createElement(this._el_108,'a',(null as any));
    this.renderer.setElementAttribute(this._el_109,'routerLink','/edit/password');
    this._RouterLinkWithHref_109_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_110 = this.renderer.createText(this._el_109,'Change Password',(null as any));
    this._text_111 = this.renderer.createText(this._el_102,'\n            ',(null as any));
    this._el_112 = this.renderer.createElement(this._el_102,'li',(null as any));
    this.renderer.setElementAttribute(this._el_112,'class','divider');
    this.renderer.setElementAttribute(this._el_112,'role','separator');
    this._text_113 = this.renderer.createText(this._el_102,'\n            ',(null as any));
    this._el_114 = this.renderer.createElement(this._el_102,'li',(null as any));
    this._el_115 = this.renderer.createElement(this._el_114,'a',(null as any));
    this.renderer.setElementAttribute(this._el_115,'id','logout');
    this._el_116 = this.renderer.createElement(this._el_115,'span',(null as any));
    this.renderer.setElementAttribute(this._el_116,'class','fa fa-sign-in');
    this._text_117 = this.renderer.createText(this._el_115,' Logout',(null as any));
    this._text_118 = this.renderer.createText(this._el_102,'\n          ',(null as any));
    this._text_119 = this.renderer.createText(this._el_96,'\n        ',(null as any));
    this._text_120 = this.renderer.createText(this._el_94,'\n      ',(null as any));
    this._text_121 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._text_122 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_123 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_124 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_125 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_126 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_127 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_47,'click',this.eventHandler(this._handle_click_47_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_51,'click',this.eventHandler(this._handle_click_51_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_81,'click',this.eventHandler(this._handle_click_81_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_87,'click',this.eventHandler(this._handle_click_87_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_105,'click',this.eventHandler(this._handle_click_105_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_109,'click',this.eventHandler(this._handle_click_109_0.bind(this)));
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_115,'click',this.eventHandler(this._handle_click_115_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._el_104,
      this._el_105,
      this._text_106,
      this._text_107,
      this._el_108,
      this._el_109,
      this._text_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._el_114,
      this._el_115,
      this._el_116,
      this._text_117,
      this._text_118,
      this._text_119,
      this._text_120,
      this._text_121,
      this._text_122,
      this._text_123,
      this._text_124,
      this._el_125,
      this._el_126,
      this._el_127
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.RouterLinkWithHref) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_19_3; }
    if (((token === import11.RouterLinkWithHref) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._RouterLinkWithHref_47_3; }
    if (((token === import11.RouterLinkWithHref) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._RouterLinkWithHref_51_3; }
    if (((token === import11.RouterLinkWithHref) && ((81 <= requestNodeIndex) && (requestNodeIndex <= 82)))) { return this._RouterLinkWithHref_81_3; }
    if (((token === import11.RouterLinkWithHref) && ((87 <= requestNodeIndex) && (requestNodeIndex <= 88)))) { return this._RouterLinkWithHref_87_3; }
    if (((token === import11.RouterLinkWithHref) && ((105 <= requestNodeIndex) && (requestNodeIndex <= 106)))) { return this._RouterLinkWithHref_105_3; }
    if (((token === import11.RouterLinkWithHref) && ((109 <= requestNodeIndex) && (requestNodeIndex <= 110)))) { return this._RouterLinkWithHref_109_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_19_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_19_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_4:any = '/member/new';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RouterLinkWithHref_47_3.routerLink = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_47_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_7:any = '/member/list';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkWithHref_51_3.routerLink = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_51_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_10:any = '/scheme/new';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._RouterLinkWithHref_81_3.routerLink = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_81_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_13:any = '/plan/new';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._RouterLinkWithHref_87_3.routerLink = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_87_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_17:any = '/edit/profile';
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._RouterLinkWithHref_105_3.routerLink = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_105_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_20:any = '/edit/password';
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._RouterLinkWithHref_109_3.routerLink = currVal_20;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_20,currVal_20);
      this._expr_20 = currVal_20;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_109_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_19_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_19,'href',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._RouterLinkWithHref_47_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_47,'href',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._RouterLinkWithHref_51_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_51,'href',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.URL,currVal_8));
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._RouterLinkWithHref_81_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_81,'href',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.URL,currVal_11));
      this._expr_11 = currVal_11;
    }
    const currVal_14:any = this._RouterLinkWithHref_87_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_87,'href',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.URL,currVal_14));
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = import4.interpolate(1,'',this.context.userName,' ');
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_99,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_18:any = this._RouterLinkWithHref_105_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementProperty(this._el_105,'href',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.URL,currVal_18));
      this._expr_18 = currVal_18;
    }
    const currVal_21:any = this._RouterLinkWithHref_109_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementProperty(this._el_109,'href',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.URL,currVal_21));
      this._expr_21 = currVal_21;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_19_3.ngOnDestroy();
    this._RouterLinkWithHref_47_3.ngOnDestroy();
    this._RouterLinkWithHref_51_3.ngOnDestroy();
    this._RouterLinkWithHref_81_3.ngOnDestroy();
    this._RouterLinkWithHref_87_3.ngOnDestroy();
    this._RouterLinkWithHref_105_3.ngOnDestroy();
    this._RouterLinkWithHref_109_3.ngOnDestroy();
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_19_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_47_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_51_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_51_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_81_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_81_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_87_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_87_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_105_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_105_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_109_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_109_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_115_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onLogout()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HeaderComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HeaderComponent> {
  if ((renderType_HeaderComponent === (null as any))) { (renderType_HeaderComponent = viewUtils.createRenderComponentType('/Users/prasadsawant/Sites/fintech_mean/frontend/app/header/header.component.html',0,import9.ViewEncapsulation.Emulated,styles_HeaderComponent,{})); }
  return new _View_HeaderComponent0(viewUtils,parentInjector,declarationEl);
}