/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '@angular/common/src/localization';
import * as import10 from '@angular/core/src/application_init';
import * as import11 from '@angular/core/src/testability/testability';
import * as import12 from '@angular/core/src/application_ref';
import * as import13 from '@angular/core/src/linker/compiler';
import * as import14 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import15 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import16 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import17 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import18 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import19 from '@angular/core/src/linker/view_utils';
import * as import20 from '@angular/platform-browser/src/browser/title';
import * as import21 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import22 from '@angular/http/src/backends/browser_xhr';
import * as import23 from '@angular/http/src/base_response_options';
import * as import24 from '@angular/http/src/backends/xhr_backend';
import * as import25 from '@angular/http/src/base_request_options';
import * as import26 from '@angular/forms/src/form_builder';
import * as import27 from '@angular/common/src/location/location';
import * as import28 from '@angular/router/src/url_tree';
import * as import29 from '@angular/router/src/router_outlet_map';
import * as import30 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import31 from './auth/auth.service';
import * as import32 from './auth/can.activate.via.auth.guard';
import * as import33 from './auth/user.service';
import * as import34 from './error/error.service';
import * as import35 from './member/member.service';
import * as import36 from './scheme/scheme.service';
import * as import37 from './notification/notification.service';
import * as import38 from './fixedDeposit/fixedDeposit.service';
import * as import39 from '@angular/core/src/di/injector';
import * as import40 from './auth/authentication.component.ngfactory';
import * as import41 from './auth/user.profile.edit.component.ngfactory';
import * as import42 from './auth/user.password.edit.component.ngfactory';
import * as import43 from './member/add.new.member.component.ngfactory';
import * as import44 from './member/list.member.component.ngfactory';
import * as import45 from './member/edit.member.component.ngfactory';
import * as import46 from './member/view.member.component.ngfactory';
import * as import47 from './scheme/add.new.scheme.component.ngfactory';
import * as import48 from './scheme/add.new.plan.component.ngfactory';
import * as import49 from './app.component.ngfactory';
import * as import50 from '@angular/core/src/application_tokens';
import * as import51 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import52 from '@angular/platform-browser/src/dom/events/key_events';
import * as import53 from '@angular/core/src/zone/ng_zone';
import * as import54 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import55 from '@angular/common/src/location/platform_location';
import * as import56 from '@angular/common/src/location/location_strategy';
import * as import57 from './auth/authentication.component';
import * as import58 from './auth/user.profile.edit.component';
import * as import59 from './auth/user.password.edit.component';
import * as import60 from './member/add.new.member.component';
import * as import61 from './member/list.member.component';
import * as import62 from './member/edit.member.component';
import * as import63 from './member/view.member.component';
import * as import64 from './scheme/add.new.scheme.component';
import * as import65 from './scheme/add.new.plan.component';
import * as import66 from '@angular/router/src/router';
import * as import67 from '@angular/core/src/console';
import * as import68 from '@angular/core/src/i18n/tokens';
import * as import69 from '@angular/core/src/error_handler';
import * as import70 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import71 from '@angular/platform-browser/src/dom/animation_driver';
import * as import72 from '@angular/core/src/render/api';
import * as import73 from '@angular/core/src/security';
import * as import74 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import75 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import76 from '@angular/http/src/interfaces';
import * as import77 from '@angular/http/src/http';
import * as import78 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import79 from '@angular/router/src/router_config_loader';
import * as import80 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _ReactiveFormsModule_6:import6.ReactiveFormsModule;
  _ROUTER_FORROOT_GUARD_7:any;
  _RouterModule_8:import8.RouterModule;
  _AppModule_9:import1.AppModule;
  __LOCALE_ID_10:any;
  __NgLocalization_11:import9.NgLocaleLocalization;
  _ErrorHandler_12:any;
  _ApplicationInitStatus_13:import10.ApplicationInitStatus;
  _Testability_14:import11.Testability;
  _ApplicationRef__15:import12.ApplicationRef_;
  __ApplicationRef_16:any;
  __Compiler_17:import13.Compiler;
  __APP_ID_18:any;
  __DOCUMENT_19:any;
  __HAMMER_GESTURE_CONFIG_20:import14.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_21:any[];
  __EventManager_22:import15.EventManager;
  __DomSharedStylesHost_23:import16.DomSharedStylesHost;
  __AnimationDriver_24:any;
  __DomRootRenderer_25:import17.DomRootRenderer_;
  __RootRenderer_26:any;
  __DomSanitizer_27:import18.DomSanitizerImpl;
  __Sanitizer_28:any;
  __ViewUtils_29:import19.ViewUtils;
  __IterableDiffers_30:any;
  __KeyValueDiffers_31:any;
  __SharedStylesHost_32:any;
  __Title_33:import20.Title;
  __RadioControlRegistry_34:import21.RadioControlRegistry;
  __BrowserXhr_35:import22.BrowserXhr;
  __ResponseOptions_36:import23.BaseResponseOptions;
  __XSRFStrategy_37:any;
  __XHRBackend_38:import24.XHRBackend;
  __RequestOptions_39:import25.BaseRequestOptions;
  __Http_40:any;
  __FormBuilder_41:import26.FormBuilder;
  __ROUTER_CONFIGURATION_42:any;
  __LocationStrategy_43:any;
  __Location_44:import27.Location;
  __UrlSerializer_45:import28.DefaultUrlSerializer;
  __RouterOutletMap_46:import29.RouterOutletMap;
  __NgModuleFactoryLoader_47:import30.SystemJsNgModuleLoader;
  __ROUTES_48:any[];
  __Router_49:any;
  __ActivatedRoute_50:any;
  __APP_BOOTSTRAP_LISTENER_51:any[];
  __AuthService_52:import31.AuthService;
  __CanActivateViaAuthGuard_53:import32.CanActivateViaAuthGuard;
  __UserService_54:import33.UserService;
  __ErrorService_55:import34.ErrorService;
  __MemberService_56:import35.MemberService;
  __SchemeService_57:import36.SchemeService;
  __NotificationService_58:import37.NotificationService;
  __FixedDepositService_59:import38.FixedDepositService;
  constructor(parent:import39.Injector) {
    super(parent,[
      import40.AuthenticationComponentNgFactory,
      import41.UserProfileEditComponentNgFactory,
      import42.UserPasswordEditComponentNgFactory,
      import43.AddNewMemberComponentNgFactory,
      import44.ListMemberComponentNgFactory,
      import45.EditMemberComponentNgFactory,
      import46.ViewMemberComponentNgFactory,
      import47.AddNewSchemeComponentNgFactory,
      import48.AddNewPlanComponentNgFactory,
      import49.AppComponentNgFactory
    ]
    ,[import49.AppComponentNgFactory]);
  }
  get _LOCALE_ID_10():any {
    if ((this.__LOCALE_ID_10 == (null as any))) { (this.__LOCALE_ID_10 = 'en-US'); }
    return this.__LOCALE_ID_10;
  }
  get _NgLocalization_11():import9.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == (null as any))) { (this.__NgLocalization_11 = new import9.NgLocaleLocalization(this._LOCALE_ID_10)); }
    return this.__NgLocalization_11;
  }
  get _ApplicationRef_16():any {
    if ((this.__ApplicationRef_16 == (null as any))) { (this.__ApplicationRef_16 = this._ApplicationRef__15); }
    return this.__ApplicationRef_16;
  }
  get _Compiler_17():import13.Compiler {
    if ((this.__Compiler_17 == (null as any))) { (this.__Compiler_17 = new import13.Compiler()); }
    return this.__Compiler_17;
  }
  get _APP_ID_18():any {
    if ((this.__APP_ID_18 == (null as any))) { (this.__APP_ID_18 = import50._appIdRandomProviderFactory()); }
    return this.__APP_ID_18;
  }
  get _DOCUMENT_19():any {
    if ((this.__DOCUMENT_19 == (null as any))) { (this.__DOCUMENT_19 = import4._document()); }
    return this.__DOCUMENT_19;
  }
  get _HAMMER_GESTURE_CONFIG_20():import14.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_20 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_20 = new import14.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_20;
  }
  get _EVENT_MANAGER_PLUGINS_21():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_21 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_21 = [
      new import51.DomEventsPlugin(),
      new import52.KeyEventsPlugin(),
      new import14.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_20)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_21;
  }
  get _EventManager_22():import15.EventManager {
    if ((this.__EventManager_22 == (null as any))) { (this.__EventManager_22 = new import15.EventManager(this._EVENT_MANAGER_PLUGINS_21,this.parent.get(import53.NgZone))); }
    return this.__EventManager_22;
  }
  get _DomSharedStylesHost_23():import16.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_23 == (null as any))) { (this.__DomSharedStylesHost_23 = new import16.DomSharedStylesHost(this._DOCUMENT_19)); }
    return this.__DomSharedStylesHost_23;
  }
  get _AnimationDriver_24():any {
    if ((this.__AnimationDriver_24 == (null as any))) { (this.__AnimationDriver_24 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_24;
  }
  get _DomRootRenderer_25():import17.DomRootRenderer_ {
    if ((this.__DomRootRenderer_25 == (null as any))) { (this.__DomRootRenderer_25 = new import17.DomRootRenderer_(this._DOCUMENT_19,this._EventManager_22,this._DomSharedStylesHost_23,this._AnimationDriver_24)); }
    return this.__DomRootRenderer_25;
  }
  get _RootRenderer_26():any {
    if ((this.__RootRenderer_26 == (null as any))) { (this.__RootRenderer_26 = import54._createConditionalRootRenderer(this._DomRootRenderer_25,this.parent.get(import54.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_26;
  }
  get _DomSanitizer_27():import18.DomSanitizerImpl {
    if ((this.__DomSanitizer_27 == (null as any))) { (this.__DomSanitizer_27 = new import18.DomSanitizerImpl()); }
    return this.__DomSanitizer_27;
  }
  get _Sanitizer_28():any {
    if ((this.__Sanitizer_28 == (null as any))) { (this.__Sanitizer_28 = this._DomSanitizer_27); }
    return this.__Sanitizer_28;
  }
  get _ViewUtils_29():import19.ViewUtils {
    if ((this.__ViewUtils_29 == (null as any))) { (this.__ViewUtils_29 = new import19.ViewUtils(this._RootRenderer_26,this._APP_ID_18,this._Sanitizer_28)); }
    return this.__ViewUtils_29;
  }
  get _IterableDiffers_30():any {
    if ((this.__IterableDiffers_30 == (null as any))) { (this.__IterableDiffers_30 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_30;
  }
  get _KeyValueDiffers_31():any {
    if ((this.__KeyValueDiffers_31 == (null as any))) { (this.__KeyValueDiffers_31 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_31;
  }
  get _SharedStylesHost_32():any {
    if ((this.__SharedStylesHost_32 == (null as any))) { (this.__SharedStylesHost_32 = this._DomSharedStylesHost_23); }
    return this.__SharedStylesHost_32;
  }
  get _Title_33():import20.Title {
    if ((this.__Title_33 == (null as any))) { (this.__Title_33 = new import20.Title()); }
    return this.__Title_33;
  }
  get _RadioControlRegistry_34():import21.RadioControlRegistry {
    if ((this.__RadioControlRegistry_34 == (null as any))) { (this.__RadioControlRegistry_34 = new import21.RadioControlRegistry()); }
    return this.__RadioControlRegistry_34;
  }
  get _BrowserXhr_35():import22.BrowserXhr {
    if ((this.__BrowserXhr_35 == (null as any))) { (this.__BrowserXhr_35 = new import22.BrowserXhr()); }
    return this.__BrowserXhr_35;
  }
  get _ResponseOptions_36():import23.BaseResponseOptions {
    if ((this.__ResponseOptions_36 == (null as any))) { (this.__ResponseOptions_36 = new import23.BaseResponseOptions()); }
    return this.__ResponseOptions_36;
  }
  get _XSRFStrategy_37():any {
    if ((this.__XSRFStrategy_37 == (null as any))) { (this.__XSRFStrategy_37 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_37;
  }
  get _XHRBackend_38():import24.XHRBackend {
    if ((this.__XHRBackend_38 == (null as any))) { (this.__XHRBackend_38 = new import24.XHRBackend(this._BrowserXhr_35,this._ResponseOptions_36,this._XSRFStrategy_37)); }
    return this.__XHRBackend_38;
  }
  get _RequestOptions_39():import25.BaseRequestOptions {
    if ((this.__RequestOptions_39 == (null as any))) { (this.__RequestOptions_39 = new import25.BaseRequestOptions()); }
    return this.__RequestOptions_39;
  }
  get _Http_40():any {
    if ((this.__Http_40 == (null as any))) { (this.__Http_40 = import7.httpFactory(this._XHRBackend_38,this._RequestOptions_39)); }
    return this.__Http_40;
  }
  get _FormBuilder_41():import26.FormBuilder {
    if ((this.__FormBuilder_41 == (null as any))) { (this.__FormBuilder_41 = new import26.FormBuilder()); }
    return this.__FormBuilder_41;
  }
  get _ROUTER_CONFIGURATION_42():any {
    if ((this.__ROUTER_CONFIGURATION_42 == (null as any))) { (this.__ROUTER_CONFIGURATION_42 = {}); }
    return this.__ROUTER_CONFIGURATION_42;
  }
  get _LocationStrategy_43():any {
    if ((this.__LocationStrategy_43 == (null as any))) { (this.__LocationStrategy_43 = import8.provideLocationStrategy(this.parent.get(import55.PlatformLocation),this.parent.get(import56.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_42)); }
    return this.__LocationStrategy_43;
  }
  get _Location_44():import27.Location {
    if ((this.__Location_44 == (null as any))) { (this.__Location_44 = new import27.Location(this._LocationStrategy_43)); }
    return this.__Location_44;
  }
  get _UrlSerializer_45():import28.DefaultUrlSerializer {
    if ((this.__UrlSerializer_45 == (null as any))) { (this.__UrlSerializer_45 = new import28.DefaultUrlSerializer()); }
    return this.__UrlSerializer_45;
  }
  get _RouterOutletMap_46():import29.RouterOutletMap {
    if ((this.__RouterOutletMap_46 == (null as any))) { (this.__RouterOutletMap_46 = new import29.RouterOutletMap()); }
    return this.__RouterOutletMap_46;
  }
  get _NgModuleFactoryLoader_47():import30.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_47 == (null as any))) { (this.__NgModuleFactoryLoader_47 = new import30.SystemJsNgModuleLoader(this._Compiler_17,this.parent.get(import30.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_47;
  }
  get _ROUTES_48():any[] {
      if ((this.__ROUTES_48 == (null as any))) { (this.__ROUTES_48 = [[
        {
          path: '',
          component: import57.AuthenticationComponent,
          pathMatch: 'full'
        }
        ,
        {
          path: 'edit/profile',
          component: import58.UserProfileEditComponent,
          canActivate: [import32.CanActivateViaAuthGuard],
          pathMatch: 'full'
        }
        ,
        {
          path: 'edit/password',
          component: import59.UserPasswordEditComponent,
          canActivate: [import32.CanActivateViaAuthGuard],
          pathMatch: 'full'
        }
        ,
        {
          path: 'member/new',
          component: import60.AddNewMemberComponent,
          canActivate: [import32.CanActivateViaAuthGuard],
          pathMatch: 'full'
        }
        ,
        {
          path: 'member/list',
          component: import61.ListMemberComponent,
          canActivate: [import32.CanActivateViaAuthGuard],
          pathMatch: 'full'
        }
        ,
        {
          path: 'member/edit/:id',
          component: import62.EditMemberComponent,
          canActivate: [import32.CanActivateViaAuthGuard],
          pathMatch: 'full'
        }
        ,
        {
          path: 'member/view/:id',
          component: import63.ViewMemberComponent,
          canActivate: [import32.CanActivateViaAuthGuard],
          pathMatch: 'full'
        }
        ,
        {
          path: 'scheme/new',
          component: import64.AddNewSchemeComponent,
          canActivate: [import32.CanActivateViaAuthGuard],
          pathMatch: 'full'
        }
        ,
        {
          path: 'plan/new',
          component: import65.AddNewPlanComponent,
          canActivate: [import32.CanActivateViaAuthGuard],
          pathMatch: 'full'
        }

      ]
    ]); }
    return this.__ROUTES_48;
  }
  get _Router_49():any {
    if ((this.__Router_49 == (null as any))) { (this.__Router_49 = import8.setupRouter(this._ApplicationRef_16,this._UrlSerializer_45,this._RouterOutletMap_46,this._Location_44,this,this._NgModuleFactoryLoader_47,this._Compiler_17,this._ROUTES_48,this._ROUTER_CONFIGURATION_42)); }
    return this.__Router_49;
  }
  get _ActivatedRoute_50():any {
    if ((this.__ActivatedRoute_50 == (null as any))) { (this.__ActivatedRoute_50 = import8.rootRoute(this._Router_49)); }
    return this.__ActivatedRoute_50;
  }
  get _APP_BOOTSTRAP_LISTENER_51():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_51 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_51 = [import8.initialRouterNavigation(this._Router_49,this._ROUTER_CONFIGURATION_42)]); }
    return this.__APP_BOOTSTRAP_LISTENER_51;
  }
  get _AuthService_52():import31.AuthService {
    if ((this.__AuthService_52 == (null as any))) { (this.__AuthService_52 = new import31.AuthService(this._Http_40,this._Router_49)); }
    return this.__AuthService_52;
  }
  get _CanActivateViaAuthGuard_53():import32.CanActivateViaAuthGuard {
    if ((this.__CanActivateViaAuthGuard_53 == (null as any))) { (this.__CanActivateViaAuthGuard_53 = new import32.CanActivateViaAuthGuard(this._AuthService_52,this._Router_49)); }
    return this.__CanActivateViaAuthGuard_53;
  }
  get _UserService_54():import33.UserService {
    if ((this.__UserService_54 == (null as any))) { (this.__UserService_54 = new import33.UserService(this._Http_40)); }
    return this.__UserService_54;
  }
  get _ErrorService_55():import34.ErrorService {
    if ((this.__ErrorService_55 == (null as any))) { (this.__ErrorService_55 = new import34.ErrorService()); }
    return this.__ErrorService_55;
  }
  get _MemberService_56():import35.MemberService {
    if ((this.__MemberService_56 == (null as any))) { (this.__MemberService_56 = new import35.MemberService(this._Http_40,this._ErrorService_55)); }
    return this.__MemberService_56;
  }
  get _SchemeService_57():import36.SchemeService {
    if ((this.__SchemeService_57 == (null as any))) { (this.__SchemeService_57 = new import36.SchemeService(this._Http_40)); }
    return this.__SchemeService_57;
  }
  get _NotificationService_58():import37.NotificationService {
    if ((this.__NotificationService_58 == (null as any))) { (this.__NotificationService_58 = new import37.NotificationService()); }
    return this.__NotificationService_58;
  }
  get _FixedDepositService_59():import38.FixedDepositService {
    if ((this.__FixedDepositService_59 == (null as any))) { (this.__FixedDepositService_59 = new import38.FixedDepositService(this._Http_40)); }
    return this.__FixedDepositService_59;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._ReactiveFormsModule_6 = new import6.ReactiveFormsModule();
    this._ROUTER_FORROOT_GUARD_7 = import8.provideForRootGuard(this.parent.get(import66.Router,(null as any)));
    this._RouterModule_8 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_7);
    this._AppModule_9 = new import1.AppModule();
    this._ErrorHandler_12 = import4.errorHandler();
    this._ApplicationInitStatus_13 = new import10.ApplicationInitStatus(this.parent.get(import10.APP_INITIALIZER,(null as any)));
    this._Testability_14 = new import11.Testability(this.parent.get(import53.NgZone));
    this._ApplicationRef__15 = new import12.ApplicationRef_(this.parent.get(import53.NgZone),this.parent.get(import67.Console),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_13,this.parent.get(import11.TestabilityRegistry,(null as any)),this._Testability_14);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_6; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_7; }
    if ((token === import8.RouterModule)) { return this._RouterModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import68.LOCALE_ID)) { return this._LOCALE_ID_10; }
    if ((token === import9.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import69.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import10.ApplicationInitStatus)) { return this._ApplicationInitStatus_13; }
    if ((token === import11.Testability)) { return this._Testability_14; }
    if ((token === import12.ApplicationRef_)) { return this._ApplicationRef__15; }
    if ((token === import12.ApplicationRef)) { return this._ApplicationRef_16; }
    if ((token === import13.Compiler)) { return this._Compiler_17; }
    if ((token === import50.APP_ID)) { return this._APP_ID_18; }
    if ((token === import70.DOCUMENT)) { return this._DOCUMENT_19; }
    if ((token === import14.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_20; }
    if ((token === import15.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_21; }
    if ((token === import15.EventManager)) { return this._EventManager_22; }
    if ((token === import16.DomSharedStylesHost)) { return this._DomSharedStylesHost_23; }
    if ((token === import71.AnimationDriver)) { return this._AnimationDriver_24; }
    if ((token === import17.DomRootRenderer)) { return this._DomRootRenderer_25; }
    if ((token === import72.RootRenderer)) { return this._RootRenderer_26; }
    if ((token === import18.DomSanitizer)) { return this._DomSanitizer_27; }
    if ((token === import73.Sanitizer)) { return this._Sanitizer_28; }
    if ((token === import19.ViewUtils)) { return this._ViewUtils_29; }
    if ((token === import74.IterableDiffers)) { return this._IterableDiffers_30; }
    if ((token === import75.KeyValueDiffers)) { return this._KeyValueDiffers_31; }
    if ((token === import16.SharedStylesHost)) { return this._SharedStylesHost_32; }
    if ((token === import20.Title)) { return this._Title_33; }
    if ((token === import21.RadioControlRegistry)) { return this._RadioControlRegistry_34; }
    if ((token === import22.BrowserXhr)) { return this._BrowserXhr_35; }
    if ((token === import23.ResponseOptions)) { return this._ResponseOptions_36; }
    if ((token === import76.XSRFStrategy)) { return this._XSRFStrategy_37; }
    if ((token === import24.XHRBackend)) { return this._XHRBackend_38; }
    if ((token === import25.RequestOptions)) { return this._RequestOptions_39; }
    if ((token === import77.Http)) { return this._Http_40; }
    if ((token === import26.FormBuilder)) { return this._FormBuilder_41; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_42; }
    if ((token === import56.LocationStrategy)) { return this._LocationStrategy_43; }
    if ((token === import27.Location)) { return this._Location_44; }
    if ((token === import28.UrlSerializer)) { return this._UrlSerializer_45; }
    if ((token === import29.RouterOutletMap)) { return this._RouterOutletMap_46; }
    if ((token === import78.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_47; }
    if ((token === import79.ROUTES)) { return this._ROUTES_48; }
    if ((token === import66.Router)) { return this._Router_49; }
    if ((token === import80.ActivatedRoute)) { return this._ActivatedRoute_50; }
    if ((token === import50.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_51; }
    if ((token === import31.AuthService)) { return this._AuthService_52; }
    if ((token === import32.CanActivateViaAuthGuard)) { return this._CanActivateViaAuthGuard_53; }
    if ((token === import33.UserService)) { return this._UserService_54; }
    if ((token === import34.ErrorService)) { return this._ErrorService_55; }
    if ((token === import35.MemberService)) { return this._MemberService_56; }
    if ((token === import36.SchemeService)) { return this._SchemeService_57; }
    if ((token === import37.NotificationService)) { return this._NotificationService_58; }
    if ((token === import38.FixedDepositService)) { return this._FixedDepositService_59; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__15.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);