/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './authentication.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from './user.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './authentication.component.css.shim';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/forms/src/directives/ng_form';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from '@angular/forms/src/directives/default_value_accessor';
import * as import19 from '@angular/forms/src/directives/validators';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/forms/src/validators';
import * as import23 from '@angular/forms/src/directives/control_value_accessor';
import * as import24 from '@angular/forms/src/directives/ng_control';
import * as import25 from '@angular/forms/src/directives/control_container';
import * as import26 from '../header/header.component';
import * as import27 from '../header/header.component.ngfactory';
var renderType_AuthenticationComponent_Host:import0.RenderComponentType = (null as any);
class _View_AuthenticationComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AuthenticationComponent_0_4:import3.AuthenticationComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AuthenticationComponent_Host0,renderType_AuthenticationComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-authentication',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AuthenticationComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AuthenticationComponent_0_4 = new import3.AuthenticationComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.UserService));
    this._appEl_0.initComponent(this._AuthenticationComponent_0_4,[],compView_0);
    compView_0.create(this._AuthenticationComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AuthenticationComponent) && (0 === requestNodeIndex))) { return this._AuthenticationComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._AuthenticationComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AuthenticationComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AuthenticationComponent_Host === (null as any))) { (renderType_AuthenticationComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_AuthenticationComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AuthenticationComponentNgFactory:import12.ComponentFactory<import3.AuthenticationComponent> = new import12.ComponentFactory<import3.AuthenticationComponent>('app-authentication',viewFactory_AuthenticationComponent_Host0,import3.AuthenticationComponent);
const styles_AuthenticationComponent:any[] = [import13.styles];
var renderType_AuthenticationComponent:import0.RenderComponentType = (null as any);
class _View_AuthenticationComponent0 extends import1.AppView<import3.AuthenticationComponent> {
  _el_0:any;
  _el_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import14.NgIf;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import14.NgIf;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AuthenticationComponent0,renderType_AuthenticationComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_4 = new import2.AppElement(4,(null as any),this,this._anchor_4);
    this._TemplateRef_4_5 = new import15.TemplateRef_(this._appEl_4,viewFactory_AuthenticationComponent1);
    this._NgIf_4_6 = new import14.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_6 = new import2.AppElement(6,(null as any),this,this._anchor_6);
    this._TemplateRef_6_5 = new import15.TemplateRef_(this._appEl_6,viewFactory_AuthenticationComponent3);
    this._NgIf_6_6 = new import14.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._el_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import14.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import15.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import14.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:boolean = !this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_4_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_6_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_AuthenticationComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AuthenticationComponent> {
  if ((renderType_AuthenticationComponent === (null as any))) { (renderType_AuthenticationComponent = viewUtils.createRenderComponentType('/Users/prasadsawant/Sites/fintech_mean/frontend/app/auth/authentication.component.html',0,import11.ViewEncapsulation.Emulated,styles_AuthenticationComponent,{})); }
  return new _View_AuthenticationComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_AuthenticationComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _NgForm_10_3:import16.NgForm;
  _ControlContainer_10_4:any;
  _NgControlStatusGroup_10_5:import17.NgControlStatusGroup;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _DefaultValueAccessor_17_3:import18.DefaultValueAccessor;
  _RequiredValidator_17_4:import19.RequiredValidator;
  _NG_VALIDATORS_17_5:any[];
  _NG_VALUE_ACCESSOR_17_6:any[];
  _NgModel_17_7:import20.NgModel;
  _NgControl_17_8:any;
  _NgControlStatus_17_9:import17.NgControlStatus;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _DefaultValueAccessor_25_3:import18.DefaultValueAccessor;
  _RequiredValidator_25_4:import19.RequiredValidator;
  _NG_VALIDATORS_25_5:any[];
  _NG_VALUE_ACCESSOR_25_6:any[];
  _NgModel_25_7:import20.NgModel;
  _NgControl_25_8:any;
  _NgControlStatus_25_9:import17.NgControlStatus;
  _text_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import14.NgIf;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AuthenticationComponent1,renderType_AuthenticationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','jumbotron text-center');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h1',(null as any));
    this._el_3 = this.renderer.createElement(this._el_2,'span',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','fa fa-inr');
    this._text_4 = this.renderer.createText(this._el_2,' Capital One',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','row');
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','col-xs-6 col-md-4 col-md-offset-4');
    this._text_9 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'form',(null as any));
    this.renderer.setElementAttribute(this._el_10,'data-dismiss','modal');
    this._NgForm_10_3 = new import16.NgForm((null as any),(null as any));
    this._ControlContainer_10_4 = this._NgForm_10_3;
    this._NgControlStatusGroup_10_5 = new import17.NgControlStatusGroup(this._ControlContainer_10_4);
    this._text_11 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','form-group');
    this._text_13 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'label',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Username',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_12,'input',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','form-control');
    this.renderer.setElementAttribute(this._el_17,'id','username');
    this.renderer.setElementAttribute(this._el_17,'name','username');
    this.renderer.setElementAttribute(this._el_17,'ngModel','');
    this.renderer.setElementAttribute(this._el_17,'placeholder','Enter your username');
    this.renderer.setElementAttribute(this._el_17,'required','true');
    this.renderer.setElementAttribute(this._el_17,'type','text');
    this._DefaultValueAccessor_17_3 = new import18.DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_17));
    this._RequiredValidator_17_4 = new import19.RequiredValidator();
    this._NG_VALIDATORS_17_5 = [this._RequiredValidator_17_4];
    this._NG_VALUE_ACCESSOR_17_6 = [this._DefaultValueAccessor_17_3];
    this._NgModel_17_7 = new import20.NgModel(this._ControlContainer_10_4,this._NG_VALIDATORS_17_5,(null as any),this._NG_VALUE_ACCESSOR_17_6);
    this._NgControl_17_8 = this._NgModel_17_7;
    this._NgControlStatus_17_9 = new import17.NgControlStatus(this._NgControl_17_8);
    this._text_18 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._text_19 = this.renderer.createText(this._el_10,'\n\n                ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','form-group');
    this._text_21 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'label',(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Password',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_20,'input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','form-control');
    this.renderer.setElementAttribute(this._el_25,'id','password');
    this.renderer.setElementAttribute(this._el_25,'name','password');
    this.renderer.setElementAttribute(this._el_25,'ngModel','');
    this.renderer.setElementAttribute(this._el_25,'placeholder','Enter your password');
    this.renderer.setElementAttribute(this._el_25,'required','true');
    this.renderer.setElementAttribute(this._el_25,'type','password');
    this._DefaultValueAccessor_25_3 = new import18.DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_25));
    this._RequiredValidator_25_4 = new import19.RequiredValidator();
    this._NG_VALIDATORS_25_5 = [this._RequiredValidator_25_4];
    this._NG_VALUE_ACCESSOR_25_6 = [this._DefaultValueAccessor_25_3];
    this._NgModel_25_7 = new import20.NgModel(this._ControlContainer_10_4,this._NG_VALIDATORS_25_5,(null as any),this._NG_VALUE_ACCESSOR_25_6);
    this._NgControl_25_8 = this._NgModel_25_7;
    this._NgControlStatus_25_9 = new import17.NgControlStatus(this._NgControl_25_8);
    this._text_26 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_10,'\n\n                ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_10,(null as any));
    this._appEl_28 = new import2.AppElement(28,10,this,this._anchor_28);
    this._TemplateRef_28_5 = new import15.TemplateRef_(this._appEl_28,viewFactory_AuthenticationComponent2);
    this._NgIf_28_6 = new import14.NgIf(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_10,'\n\n                ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_10,'hr',(null as any));
    this._text_31 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','btn btn-success btn-lg');
    this.renderer.setElementAttribute(this._el_32,'type','submit');
    this._text_33 = this.renderer.createText(this._el_32,'Login',(null as any));
    this._text_34 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._text_35 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_36 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_37 = this.renderer.createText(this._el_0,' \n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_10,'ngSubmit',this.eventHandler(this._handle_ngSubmit_10_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_10,'submit',this.eventHandler(this._handle_submit_10_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_10,'reset',this.eventHandler(this._handle_reset_10_2.bind(this)));
    const subscription_0:any = this._NgForm_10_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_10_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_17,'input',this.eventHandler(this._handle_input_17_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_17,'blur',this.eventHandler(this._handle_blur_17_1.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_25,'input',this.eventHandler(this._handle_input_25_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_25,'blur',this.eventHandler(this._handle_blur_25_1.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.DefaultValueAccessor) && (17 === requestNodeIndex))) { return this._DefaultValueAccessor_17_3; }
    if (((token === import19.RequiredValidator) && (17 === requestNodeIndex))) { return this._RequiredValidator_17_4; }
    if (((token === import22.NG_VALIDATORS) && (17 === requestNodeIndex))) { return this._NG_VALIDATORS_17_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (17 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_17_6; }
    if (((token === import20.NgModel) && (17 === requestNodeIndex))) { return this._NgModel_17_7; }
    if (((token === import24.NgControl) && (17 === requestNodeIndex))) { return this._NgControl_17_8; }
    if (((token === import17.NgControlStatus) && (17 === requestNodeIndex))) { return this._NgControlStatus_17_9; }
    if (((token === import18.DefaultValueAccessor) && (25 === requestNodeIndex))) { return this._DefaultValueAccessor_25_3; }
    if (((token === import19.RequiredValidator) && (25 === requestNodeIndex))) { return this._RequiredValidator_25_4; }
    if (((token === import22.NG_VALIDATORS) && (25 === requestNodeIndex))) { return this._NG_VALIDATORS_25_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (25 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_25_6; }
    if (((token === import20.NgModel) && (25 === requestNodeIndex))) { return this._NgModel_25_7; }
    if (((token === import24.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_8; }
    if (((token === import17.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_9; }
    if (((token === import15.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import14.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6; }
    if (((token === import16.NgForm) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._NgForm_10_3; }
    if (((token === import25.ControlContainer) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ControlContainer_10_4; }
    if (((token === import17.NgControlStatusGroup) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._NgControlStatusGroup_10_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_11:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._RequiredValidator_17_4.required = currVal_11;
      this._expr_11 = currVal_11;
    }
    changes = (null as any);
    const currVal_13:any = 'username';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgModel_17_7.name = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_17_7.model = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._NgModel_17_7.ngOnChanges(changes); }
    const currVal_23:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._RequiredValidator_25_4.required = currVal_23;
      this._expr_23 = currVal_23;
    }
    changes = (null as any);
    const currVal_25:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._NgModel_25_7.name = currVal_25;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_25,currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._NgModel_25_7.model = currVal_26;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_26,currVal_26);
      this._expr_26 = currVal_26;
    }
    if ((changes !== (null as any))) { this._NgModel_25_7.ngOnChanges(changes); }
    const currVal_33:any = this.parent.context.errFlag;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._NgIf_28_6.ngIf = currVal_33;
      this._expr_33 = currVal_33;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_10_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_10_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_10,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_10_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_10,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_10_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_10,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_10_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_10,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_10_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_10,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_12:any = (this._RequiredValidator_17_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementAttribute(this._el_17,'required',((currVal_12 == (null as any))? (null as any): currVal_12.toString()));
      this._expr_12 = currVal_12;
    }
    const currVal_15:any = this._NgControlStatus_17_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_17,'ng-untouched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_17_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_17,'ng-touched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_17_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_17,'ng-pristine',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_17_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_17,'ng-dirty',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_17_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_17,'ng-valid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_17_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_17,'ng-invalid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_24:any = (this._RequiredValidator_25_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementAttribute(this._el_25,'required',((currVal_24 == (null as any))? (null as any): currVal_24.toString()));
      this._expr_24 = currVal_24;
    }
    const currVal_27:any = this._NgControlStatus_25_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_25,'ng-untouched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_25_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_25,'ng-touched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_25_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_25,'ng-pristine',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_25_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_25,'ng-dirty',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_25_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_25,'ng-valid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_25_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_25,'ng-invalid',currVal_32);
      this._expr_32 = currVal_32;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_17_7.ngOnDestroy();
    this._NgModel_25_7.ngOnDestroy();
  }
  private _handle_ngSubmit_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.login(this._NgForm_10_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_10_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_10_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_10_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_10_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_17_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_17_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_17_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_25_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_25_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_25_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AuthenticationComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AuthenticationComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_AuthenticationComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AuthenticationComponent2,renderType_AuthenticationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger alert-dismissable fade in');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'aria-label','close');
    this.renderer.setElementAttribute(this._el_2,'class','close');
    this.renderer.setElementAttribute(this._el_2,'data-dismiss','alert');
    this.renderer.setElementAttribute(this._el_2,'href','#');
    this._text_3 = this.renderer.createText(this._el_2,'×',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'strong',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Error!',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,' ',this.parent.parent.context.errMessage,'\n                ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AuthenticationComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AuthenticationComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_AuthenticationComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _HeaderComponent_2_4:import26.HeaderComponent;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AuthenticationComponent3,renderType_AuthenticationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','dashboard');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'app-header',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import27.viewFactory_HeaderComponent0(this.viewUtils,this.injector(2),this._appEl_2);
    this._HeaderComponent_2_4 = new import26.HeaderComponent(this.parentInjector.get(import8.AuthService));
    this._appEl_2.initComponent(this._HeaderComponent_2_4,[],compView_2);
    compView_2.create(this._HeaderComponent_2_4,[],(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','row');
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','col-md-3');
    this._text_7 = this.renderer.createText(this._el_6,'\n            \n        ',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-md-6');
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'table',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','table table-bordered');
    this._text_12 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'tbody',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'tr',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','success');
    this._text_16 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'td',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Total Active Members:',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_15,'td',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_13,'tr',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','danger');
    this._text_25 = this.renderer.createText(this._el_24,'\n                        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'td',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Total Non-Active Members:',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n                        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_24,'td',(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'',(null as any));
    this._text_31 = this.renderer.createText(this._el_24,'\n                    ',(null as any));
    this._text_32 = this.renderer.createText(this._el_13,'\n                    ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_13,'tr',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','info');
    this._text_34 = this.renderer.createText(this._el_33,'\n                        ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'td',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Total Members:',(null as any));
    this._text_37 = this.renderer.createText(this._el_33,'\n                        ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_33,'td',(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'',(null as any));
    this._text_40 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._text_41 = this.renderer.createText(this._el_13,'\n                ',(null as any));
    this._text_42 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._text_43 = this.renderer.createText(this._el_9,'\n\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_4,'\n\n        ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','col-md-3');
    this._text_46 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_47 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.HeaderComponent) && (2 === requestNodeIndex))) { return this._HeaderComponent_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeaderComponent_2_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.activeMembers,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_21,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.parent.context.nonActiveMembers,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_30,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.parent.context.totalMembers,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_39,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AuthenticationComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AuthenticationComponent3(viewUtils,parentInjector,declarationEl);
}