/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './dashboard.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../header/header.component';
import * as import11 from '../header/header.component.ngfactory';
import * as import12 from './auth.service';
var renderType_DashboardComponent_Host:import0.RenderComponentType = (null as any);
class _View_DashboardComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _DashboardComponent_0_4:import3.DashboardComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DashboardComponent_Host0,renderType_DashboardComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-dashboard',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DashboardComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DashboardComponent_0_4 = new import3.DashboardComponent();
    this._appEl_0.initComponent(this._DashboardComponent_0_4,[],compView_0);
    compView_0.create(this._DashboardComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.DashboardComponent) && (0 === requestNodeIndex))) { return this._DashboardComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_DashboardComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_DashboardComponent_Host === (null as any))) { (renderType_DashboardComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_DashboardComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const DashboardComponentNgFactory:import9.ComponentFactory<import3.DashboardComponent> = new import9.ComponentFactory<import3.DashboardComponent>('app-dashboard',viewFactory_DashboardComponent_Host0,import3.DashboardComponent);
const styles_DashboardComponent:any[] = [];
var renderType_DashboardComponent:import0.RenderComponentType = (null as any);
class _View_DashboardComponent0 extends import1.AppView<import3.DashboardComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import10.HeaderComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DashboardComponent0,renderType_DashboardComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'app-header',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import11.viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import10.HeaderComponent(this.parentInjector.get(import12.AuthService));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,[],(null as any));
    this.init([],[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeaderComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_DashboardComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.DashboardComponent> {
  if ((renderType_DashboardComponent === (null as any))) { (renderType_DashboardComponent = viewUtils.createRenderComponentType('/Users/prasadsawant/Sites/fintech_mean/frontend/app/auth/dashboard.component.html',0,import8.ViewEncapsulation.None,styles_DashboardComponent,{})); }
  return new _View_DashboardComponent0(viewUtils,parentInjector,declarationEl);
}