/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './user.password.edit.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './user.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../header/header.component';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '@angular/forms/src/directives/ng_form';
import * as import14 from '@angular/forms/src/directives/ng_control_status';
import * as import15 from '@angular/forms/src/directives/default_value_accessor';
import * as import16 from '@angular/forms/src/directives/ng_model';
import * as import17 from '@angular/router/src/directives/router_link';
import * as import18 from '../header/header.component.ngfactory';
import * as import19 from './auth.service';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/router/src/router';
import * as import23 from '@angular/router/src/router_state';
import * as import24 from '@angular/common/src/location/location_strategy';
import * as import25 from '@angular/forms/src/directives/control_value_accessor';
import * as import26 from '@angular/forms/src/directives/ng_control';
import * as import27 from '@angular/forms/src/directives/control_container';
import * as import28 from '@angular/core/src/security';
var renderType_UserPasswordEditComponent_Host:import0.RenderComponentType = (null as any);
class _View_UserPasswordEditComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserPasswordEditComponent_0_4:import3.UserPasswordEditComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPasswordEditComponent_Host0,renderType_UserPasswordEditComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-edit-password',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserPasswordEditComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserPasswordEditComponent_0_4 = new import3.UserPasswordEditComponent(this.parentInjector.get(import8.UserService));
    this._appEl_0.initComponent(this._UserPasswordEditComponent_0_4,[],compView_0);
    compView_0.create(this._UserPasswordEditComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UserPasswordEditComponent) && (0 === requestNodeIndex))) { return this._UserPasswordEditComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._UserPasswordEditComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserPasswordEditComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UserPasswordEditComponent_Host === (null as any))) { (renderType_UserPasswordEditComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_UserPasswordEditComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserPasswordEditComponentNgFactory:import10.ComponentFactory<import3.UserPasswordEditComponent> = new import10.ComponentFactory<import3.UserPasswordEditComponent>('app-edit-password',viewFactory_UserPasswordEditComponent_Host0,import3.UserPasswordEditComponent);
const styles_UserPasswordEditComponent:any[] = [];
var renderType_UserPasswordEditComponent:import0.RenderComponentType = (null as any);
class _View_UserPasswordEditComponent0 extends import1.AppView<import3.UserPasswordEditComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import11.HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import12.NgIf;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import12.NgIf;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _el_11:any;
  _el_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _NgForm_19_3:import13.NgForm;
  _ControlContainer_19_4:any;
  _NgControlStatusGroup_19_5:import14.NgControlStatusGroup;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _DefaultValueAccessor_26_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_26_4:any[];
  _NgModel_26_5:import16.NgModel;
  _NgControl_26_6:any;
  _NgControlStatus_26_7:import14.NgControlStatus;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _DefaultValueAccessor_34_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_34_4:any[];
  _NgModel_34_5:import16.NgModel;
  _NgControl_34_6:any;
  _NgControlStatus_34_7:import14.NgControlStatus;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _DefaultValueAccessor_42_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_42_4:any[];
  _NgModel_42_5:import16.NgModel;
  _NgControl_42_6:any;
  _NgControlStatus_42_7:import14.NgControlStatus;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _RouterLinkWithHref_50_3:import17.RouterLinkWithHref;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPasswordEditComponent0,renderType_UserPasswordEditComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'app-header',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import18.viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import11.HeaderComponent(this.parentInjector.get(import19.AuthService));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,[],(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-sm-6 col-sm-offset-3');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import20.TemplateRef_(this._appEl_4,viewFactory_UserPasswordEditComponent1);
    this._NgIf_4_6 = new import12.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_6 = new import2.AppElement(6,2,this,this._anchor_6);
    this._TemplateRef_6_5 = new import20.TemplateRef_(this._appEl_6,viewFactory_UserPasswordEditComponent2);
    this._NgIf_6_6 = new import12.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_11 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_12 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_13 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_15 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','row');
    this._text_16 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','col-xs-6 col-md-4 col-md-offset-4');
    this._text_18 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'form',(null as any));
    this._NgForm_19_3 = new import13.NgForm((null as any),(null as any));
    this._ControlContainer_19_4 = this._NgForm_19_3;
    this._NgControlStatusGroup_19_5 = new import14.NgControlStatusGroup(this._ControlContainer_19_4);
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','form-group');
    this._text_22 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'label',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Old Password:',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_21,'input',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','form-control');
    this.renderer.setElementAttribute(this._el_26,'name','oldPassword');
    this.renderer.setElementAttribute(this._el_26,'ngModel','');
    this.renderer.setElementAttribute(this._el_26,'placeholder','Enter your old password');
    this.renderer.setElementAttribute(this._el_26,'type','password');
    this._DefaultValueAccessor_26_3 = new import15.DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_26));
    this._NG_VALUE_ACCESSOR_26_4 = [this._DefaultValueAccessor_26_3];
    this._NgModel_26_5 = new import16.NgModel(this._ControlContainer_19_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_26_4);
    this._NgControl_26_6 = this._NgModel_26_5;
    this._NgControlStatus_26_7 = new import14.NgControlStatus(this._NgControl_26_6);
    this._text_27 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','form-group');
    this._text_30 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'label',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'New Password:',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_29,'input',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','form-control');
    this.renderer.setElementAttribute(this._el_34,'name','newPassword');
    this.renderer.setElementAttribute(this._el_34,'ngModel','');
    this.renderer.setElementAttribute(this._el_34,'placeholder','Enter your new password');
    this.renderer.setElementAttribute(this._el_34,'type','password');
    this._DefaultValueAccessor_34_3 = new import15.DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_34));
    this._NG_VALUE_ACCESSOR_34_4 = [this._DefaultValueAccessor_34_3];
    this._NgModel_34_5 = new import16.NgModel(this._ControlContainer_19_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_34_4);
    this._NgControl_34_6 = this._NgModel_34_5;
    this._NgControlStatus_34_7 = new import14.NgControlStatus(this._NgControl_34_6);
    this._text_35 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._text_36 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','form-group');
    this._text_38 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'label',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Confirm Password:',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_37,'input',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','form-control');
    this.renderer.setElementAttribute(this._el_42,'name','confirmPassword');
    this.renderer.setElementAttribute(this._el_42,'ngModel','');
    this.renderer.setElementAttribute(this._el_42,'placeholder','Enter your new password');
    this.renderer.setElementAttribute(this._el_42,'type','password');
    this._DefaultValueAccessor_42_3 = new import15.DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_42));
    this._NG_VALUE_ACCESSOR_42_4 = [this._DefaultValueAccessor_42_3];
    this._NgModel_42_5 = new import16.NgModel(this._ControlContainer_19_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_42_4);
    this._NgControl_42_6 = this._NgModel_42_5;
    this._NgControlStatus_42_7 = new import14.NgControlStatus(this._NgControl_42_6);
    this._text_43 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._text_44 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_19,'hr',(null as any));
    this._text_46 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','btn btn-success btn-lg');
    this.renderer.setElementAttribute(this._el_47,'type','submit');
    this._text_48 = this.renderer.createText(this._el_47,'Save',(null as any));
    this._text_49 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_19,'a',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','btn btn-info btn-lg');
    this.renderer.setElementAttribute(this._el_50,'routerLink','/dashboard');
    this._RouterLinkWithHref_50_3 = new import17.RouterLinkWithHref(this.parentInjector.get(import22.Router),this.parentInjector.get(import23.ActivatedRoute),this.parentInjector.get(import24.LocationStrategy));
    this._text_51 = this.renderer.createText(this._el_50,'Cancel',(null as any));
    this._text_52 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._text_54 = this.renderer.createText(this._el_15,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_19,'ngSubmit',this.eventHandler(this._handle_ngSubmit_19_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_19,'submit',this.eventHandler(this._handle_submit_19_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_19,'reset',this.eventHandler(this._handle_reset_19_2.bind(this)));
    const subscription_0:any = this._NgForm_19_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_19_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_26,'input',this.eventHandler(this._handle_input_26_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_26,'blur',this.eventHandler(this._handle_blur_26_1.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_34,'input',this.eventHandler(this._handle_input_34_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_34,'blur',this.eventHandler(this._handle_blur_34_1.bind(this)));
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_42,'input',this.eventHandler(this._handle_input_42_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_42,'blur',this.eventHandler(this._handle_blur_42_1.bind(this)));
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_50,'click',this.eventHandler(this._handle_click_50_0.bind(this)));
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._el_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    if (((token === import20.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import12.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import20.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import12.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    if (((token === import15.DefaultValueAccessor) && (26 === requestNodeIndex))) { return this._DefaultValueAccessor_26_3; }
    if (((token === import25.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_4; }
    if (((token === import16.NgModel) && (26 === requestNodeIndex))) { return this._NgModel_26_5; }
    if (((token === import26.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_6; }
    if (((token === import14.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_7; }
    if (((token === import15.DefaultValueAccessor) && (34 === requestNodeIndex))) { return this._DefaultValueAccessor_34_3; }
    if (((token === import25.NG_VALUE_ACCESSOR) && (34 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_34_4; }
    if (((token === import16.NgModel) && (34 === requestNodeIndex))) { return this._NgModel_34_5; }
    if (((token === import26.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_6; }
    if (((token === import14.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_7; }
    if (((token === import15.DefaultValueAccessor) && (42 === requestNodeIndex))) { return this._DefaultValueAccessor_42_3; }
    if (((token === import25.NG_VALUE_ACCESSOR) && (42 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_42_4; }
    if (((token === import16.NgModel) && (42 === requestNodeIndex))) { return this._NgModel_42_5; }
    if (((token === import26.NgControl) && (42 === requestNodeIndex))) { return this._NgControl_42_6; }
    if (((token === import14.NgControlStatus) && (42 === requestNodeIndex))) { return this._NgControlStatus_42_7; }
    if (((token === import17.RouterLinkWithHref) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._RouterLinkWithHref_50_3; }
    if (((token === import13.NgForm) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._NgForm_19_3; }
    if (((token === import27.ControlContainer) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._ControlContainer_19_4; }
    if (((token === import14.NgControlStatusGroup) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._NgControlStatusGroup_19_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeaderComponent_0_4.ngOnInit(); }
    const currVal_1:any = this.context.errFlag;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.successFlag;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_6_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    changes = (null as any);
    const currVal_14:any = 'oldPassword';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_26_5.name = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgModel_26_5.model = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    if ((changes !== (null as any))) { this._NgModel_26_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_24:any = 'newPassword';
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._NgModel_34_5.name = currVal_24;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_24,currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._NgModel_34_5.model = currVal_25;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_25,currVal_25);
      this._expr_25 = currVal_25;
    }
    if ((changes !== (null as any))) { this._NgModel_34_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_34:any = 'confirmPassword';
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._NgModel_42_5.name = currVal_34;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_34,currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._NgModel_42_5.model = currVal_35;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_35,currVal_35);
      this._expr_35 = currVal_35;
    }
    if ((changes !== (null as any))) { this._NgModel_42_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_43:any = '/dashboard';
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this._RouterLinkWithHref_50_3.routerLink = currVal_43;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_43,currVal_43);
      this._expr_43 = currVal_43;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_50_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:boolean = !this.context.notificationFlag;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_6:any = this._NgControlStatusGroup_19_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_19_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_19_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_19_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_19_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_19_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_16:any = this._NgControlStatus_26_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_26_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_26_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_26_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_26_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_26_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_26:any = this._NgControlStatus_34_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_34,'ng-untouched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_34_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_34,'ng-touched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_34_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_34,'ng-pristine',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_34_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_34,'ng-dirty',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_34_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_34,'ng-valid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_34_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_34,'ng-invalid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_36:any = this._NgControlStatus_42_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_42,'ng-untouched',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_42_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_42,'ng-touched',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_42_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_42,'ng-pristine',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_42_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_42,'ng-dirty',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_42_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_42,'ng-valid',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_42_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_42,'ng-invalid',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_44:any = this._RouterLinkWithHref_50_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementProperty(this._el_50,'href',this.viewUtils.sanitizer.sanitize(import28.SecurityContext.URL,currVal_44));
      this._expr_44 = currVal_44;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_26_5.ngOnDestroy();
    this._NgModel_34_5.ngOnDestroy();
    this._NgModel_42_5.ngOnDestroy();
    this._RouterLinkWithHref_50_3.ngOnDestroy();
  }
  private _handle_ngSubmit_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSave(this._NgForm_19_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_19_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_19_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_19_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_19_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_26_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_26_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_26_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_34_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_42_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_42_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_42_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_50_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_50_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_UserPasswordEditComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UserPasswordEditComponent> {
  if ((renderType_UserPasswordEditComponent === (null as any))) { (renderType_UserPasswordEditComponent = viewUtils.createRenderComponentType('/Users/prasadsawant/Sites/fintech_mean/frontend/app/auth/user.password.edit.component.html',0,import9.ViewEncapsulation.None,styles_UserPasswordEditComponent,{})); }
  return new _View_UserPasswordEditComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_UserPasswordEditComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPasswordEditComponent1,renderType_UserPasswordEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger alert-dismissable fade in');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'aria-label','close');
    this.renderer.setElementAttribute(this._el_2,'class','close');
    this.renderer.setElementAttribute(this._el_2,'data-dismiss','alert');
    this.renderer.setElementAttribute(this._el_2,'href','#');
    this._text_3 = this.renderer.createText(this._el_2,'×',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'strong',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Error!',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,' ',this.parent.context.errMessage,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserPasswordEditComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserPasswordEditComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_UserPasswordEditComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPasswordEditComponent2,renderType_UserPasswordEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-success alert-dismissable fade in');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'aria-label','close');
    this.renderer.setElementAttribute(this._el_2,'class','close');
    this.renderer.setElementAttribute(this._el_2,'data-dismiss','alert');
    this.renderer.setElementAttribute(this._el_2,'href','#');
    this._text_3 = this.renderer.createText(this._el_2,'×',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'strong',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Success!',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,' ',this.parent.context.successMessage,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserPasswordEditComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserPasswordEditComponent2(viewUtils,parentInjector,declarationEl);
}