/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './user.profile.edit.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './user.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../header/header.component';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import14 from '@angular/forms/src/directives/ng_control_status';
import * as import15 from '@angular/forms/src/directives/default_value_accessor';
import * as import16 from '@angular/forms/src/directives/validators';
import * as import17 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import18 from '@angular/router/src/directives/router_link';
import * as import19 from '../header/header.component.ngfactory';
import * as import20 from './auth.service';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from '@angular/router/src/router';
import * as import24 from '@angular/router/src/router_state';
import * as import25 from '@angular/common/src/location/location_strategy';
import * as import26 from '@angular/forms/src/validators';
import * as import27 from '@angular/forms/src/directives/control_value_accessor';
import * as import28 from '@angular/forms/src/directives/ng_control';
import * as import29 from '@angular/forms/src/directives/control_container';
import * as import30 from '@angular/core/src/security';
var renderType_UserProfileEditComponent_Host:import0.RenderComponentType = (null as any);
class _View_UserProfileEditComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserProfileEditComponent_0_4:import3.UserProfileEditComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserProfileEditComponent_Host0,renderType_UserProfileEditComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-edit-profile',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserProfileEditComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserProfileEditComponent_0_4 = new import3.UserProfileEditComponent(this.parentInjector.get(import8.UserService));
    this._appEl_0.initComponent(this._UserProfileEditComponent_0_4,[],compView_0);
    compView_0.create(this._UserProfileEditComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UserProfileEditComponent) && (0 === requestNodeIndex))) { return this._UserProfileEditComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._UserProfileEditComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserProfileEditComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UserProfileEditComponent_Host === (null as any))) { (renderType_UserProfileEditComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_UserProfileEditComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserProfileEditComponentNgFactory:import10.ComponentFactory<import3.UserProfileEditComponent> = new import10.ComponentFactory<import3.UserProfileEditComponent>('app-edit-profile',viewFactory_UserProfileEditComponent_Host0,import3.UserProfileEditComponent);
const styles_UserProfileEditComponent:any[] = [];
var renderType_UserProfileEditComponent:import0.RenderComponentType = (null as any);
class _View_UserProfileEditComponent0 extends import1.AppView<import3.UserProfileEditComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import11.HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import12.NgIf;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import12.NgIf;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _el_11:any;
  _el_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _FormGroupDirective_19_3:import13.FormGroupDirective;
  _ControlContainer_19_4:any;
  _NgControlStatusGroup_19_5:import14.NgControlStatusGroup;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _DefaultValueAccessor_26_3:import15.DefaultValueAccessor;
  _RequiredValidator_26_4:import16.RequiredValidator;
  _NG_VALIDATORS_26_5:any[];
  _NG_VALUE_ACCESSOR_26_6:any[];
  _FormControlName_26_7:import17.FormControlName;
  _NgControl_26_8:any;
  _NgControlStatus_26_9:import14.NgControlStatus;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _DefaultValueAccessor_34_3:import15.DefaultValueAccessor;
  _RequiredValidator_34_4:import16.RequiredValidator;
  _NG_VALIDATORS_34_5:any[];
  _NG_VALUE_ACCESSOR_34_6:any[];
  _FormControlName_34_7:import17.FormControlName;
  _NgControl_34_8:any;
  _NgControlStatus_34_9:import14.NgControlStatus;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _DefaultValueAccessor_42_3:import15.DefaultValueAccessor;
  _RequiredValidator_42_4:import16.RequiredValidator;
  _NG_VALIDATORS_42_5:any[];
  _NG_VALUE_ACCESSOR_42_6:any[];
  _FormControlName_42_7:import17.FormControlName;
  _NgControl_42_8:any;
  _NgControlStatus_42_9:import14.NgControlStatus;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _DefaultValueAccessor_50_3:import15.DefaultValueAccessor;
  _RequiredValidator_50_4:import16.RequiredValidator;
  _NG_VALIDATORS_50_5:any[];
  _NG_VALUE_ACCESSOR_50_6:any[];
  _FormControlName_50_7:import17.FormControlName;
  _NgControl_50_8:any;
  _NgControlStatus_50_9:import14.NgControlStatus;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _RouterLinkWithHref_58_3:import18.RouterLinkWithHref;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_63:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_67:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserProfileEditComponent0,renderType_UserProfileEditComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'app-header',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import19.viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import11.HeaderComponent(this.parentInjector.get(import20.AuthService));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,[],(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-sm-6 col-sm-offset-3');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import21.TemplateRef_(this._appEl_4,viewFactory_UserProfileEditComponent1);
    this._NgIf_4_6 = new import12.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_6 = new import2.AppElement(6,2,this,this._anchor_6);
    this._TemplateRef_6_5 = new import21.TemplateRef_(this._appEl_6,viewFactory_UserProfileEditComponent2);
    this._NgIf_6_6 = new import12.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_11 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_12 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_13 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_15 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','row');
    this._text_16 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','col-xs-6 col-md-4 col-md-offset-4');
    this._text_18 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'form',(null as any));
    this.renderer.setElementAttribute(this._el_19,'data-dismiss','modal');
    this._FormGroupDirective_19_3 = new import13.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_19_4 = this._FormGroupDirective_19_3;
    this._NgControlStatusGroup_19_5 = new import14.NgControlStatusGroup(this._ControlContainer_19_4);
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','form-group');
    this._text_22 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'label',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'First Name:',(null as any));
    this._text_25 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_21,'input',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','form-control');
    this.renderer.setElementAttribute(this._el_26,'formControlName','firstName');
    this.renderer.setElementAttribute(this._el_26,'name','firstName');
    this.renderer.setElementAttribute(this._el_26,'ngModel','');
    this.renderer.setElementAttribute(this._el_26,'placeholder','Enter your first name');
    this.renderer.setElementAttribute(this._el_26,'required','true');
    this.renderer.setElementAttribute(this._el_26,'type','text');
    this._DefaultValueAccessor_26_3 = new import15.DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_26));
    this._RequiredValidator_26_4 = new import16.RequiredValidator();
    this._NG_VALIDATORS_26_5 = [this._RequiredValidator_26_4];
    this._NG_VALUE_ACCESSOR_26_6 = [this._DefaultValueAccessor_26_3];
    this._FormControlName_26_7 = new import17.FormControlName(this._ControlContainer_19_4,this._NG_VALIDATORS_26_5,(null as any),this._NG_VALUE_ACCESSOR_26_6);
    this._NgControl_26_8 = this._FormControlName_26_7;
    this._NgControlStatus_26_9 = new import14.NgControlStatus(this._NgControl_26_8);
    this._text_27 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','form-group');
    this._text_30 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'label',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Last Name:',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_29,'input',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','form-control');
    this.renderer.setElementAttribute(this._el_34,'formControlName','lastName');
    this.renderer.setElementAttribute(this._el_34,'name','lastName');
    this.renderer.setElementAttribute(this._el_34,'ngModel','');
    this.renderer.setElementAttribute(this._el_34,'placeholder','Enter your last name');
    this.renderer.setElementAttribute(this._el_34,'required','true');
    this.renderer.setElementAttribute(this._el_34,'type','text');
    this._DefaultValueAccessor_34_3 = new import15.DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_34));
    this._RequiredValidator_34_4 = new import16.RequiredValidator();
    this._NG_VALIDATORS_34_5 = [this._RequiredValidator_34_4];
    this._NG_VALUE_ACCESSOR_34_6 = [this._DefaultValueAccessor_34_3];
    this._FormControlName_34_7 = new import17.FormControlName(this._ControlContainer_19_4,this._NG_VALIDATORS_34_5,(null as any),this._NG_VALUE_ACCESSOR_34_6);
    this._NgControl_34_8 = this._FormControlName_34_7;
    this._NgControlStatus_34_9 = new import14.NgControlStatus(this._NgControl_34_8);
    this._text_35 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._text_36 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','form-group');
    this._text_38 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'label',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Username:',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_37,'input',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','form-control');
    this.renderer.setElementAttribute(this._el_42,'formControlName','username');
    this.renderer.setElementAttribute(this._el_42,'name','username');
    this.renderer.setElementAttribute(this._el_42,'ngModel','');
    this.renderer.setElementAttribute(this._el_42,'placeholder','Enter your username');
    this.renderer.setElementAttribute(this._el_42,'required','true');
    this.renderer.setElementAttribute(this._el_42,'type','text');
    this._DefaultValueAccessor_42_3 = new import15.DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_42));
    this._RequiredValidator_42_4 = new import16.RequiredValidator();
    this._NG_VALIDATORS_42_5 = [this._RequiredValidator_42_4];
    this._NG_VALUE_ACCESSOR_42_6 = [this._DefaultValueAccessor_42_3];
    this._FormControlName_42_7 = new import17.FormControlName(this._ControlContainer_19_4,this._NG_VALIDATORS_42_5,(null as any),this._NG_VALUE_ACCESSOR_42_6);
    this._NgControl_42_8 = this._FormControlName_42_7;
    this._NgControlStatus_42_9 = new import14.NgControlStatus(this._NgControl_42_8);
    this._text_43 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._text_44 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','form-group');
    this._text_46 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'label',(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'Mobile:',(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_45,'input',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','form-control');
    this.renderer.setElementAttribute(this._el_50,'formControlName','mobile');
    this.renderer.setElementAttribute(this._el_50,'name','mobile');
    this.renderer.setElementAttribute(this._el_50,'ngModel','');
    this.renderer.setElementAttribute(this._el_50,'placeholder','Enter your mobile number');
    this.renderer.setElementAttribute(this._el_50,'required','true');
    this.renderer.setElementAttribute(this._el_50,'type','tel');
    this._DefaultValueAccessor_50_3 = new import15.DefaultValueAccessor(this.renderer,new import22.ElementRef(this._el_50));
    this._RequiredValidator_50_4 = new import16.RequiredValidator();
    this._NG_VALIDATORS_50_5 = [this._RequiredValidator_50_4];
    this._NG_VALUE_ACCESSOR_50_6 = [this._DefaultValueAccessor_50_3];
    this._FormControlName_50_7 = new import17.FormControlName(this._ControlContainer_19_4,this._NG_VALIDATORS_50_5,(null as any),this._NG_VALUE_ACCESSOR_50_6);
    this._NgControl_50_8 = this._FormControlName_50_7;
    this._NgControlStatus_50_9 = new import14.NgControlStatus(this._NgControl_50_8);
    this._text_51 = this.renderer.createText(this._el_45,'\n            ',(null as any));
    this._text_52 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_19,'hr',(null as any));
    this._text_54 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','btn btn-success btn-lg');
    this.renderer.setElementAttribute(this._el_55,'type','submit');
    this._text_56 = this.renderer.createText(this._el_55,'Save',(null as any));
    this._text_57 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_19,'a',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','btn btn-info btn-lg');
    this.renderer.setElementAttribute(this._el_58,'routerLink','/');
    this._RouterLinkWithHref_58_3 = new import18.RouterLinkWithHref(this.parentInjector.get(import23.Router),this.parentInjector.get(import24.ActivatedRoute),this.parentInjector.get(import25.LocationStrategy));
    this._text_59 = this.renderer.createText(this._el_58,'Cancel',(null as any));
    this._text_60 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_17,'\n    ',(null as any));
    this._text_62 = this.renderer.createText(this._el_15,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_19,'ngSubmit',this.eventHandler(this._handle_ngSubmit_19_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_19,'submit',this.eventHandler(this._handle_submit_19_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_19,'reset',this.eventHandler(this._handle_reset_19_2.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_19_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_19_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_26,'ngModelChange',this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_26,'input',this.eventHandler(this._handle_input_26_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_26,'blur',this.eventHandler(this._handle_blur_26_2.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    const subscription_1:any = this._FormControlName_26_7.update.subscribe(this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_34,'ngModelChange',this.eventHandler(this._handle_ngModelChange_34_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_34,'input',this.eventHandler(this._handle_input_34_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_34,'blur',this.eventHandler(this._handle_blur_34_2.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    const subscription_2:any = this._FormControlName_34_7.update.subscribe(this.eventHandler(this._handle_ngModelChange_34_0.bind(this)));
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_42,'ngModelChange',this.eventHandler(this._handle_ngModelChange_42_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_42,'input',this.eventHandler(this._handle_input_42_1.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_42,'blur',this.eventHandler(this._handle_blur_42_2.bind(this)));
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    const subscription_3:any = this._FormControlName_42_7.update.subscribe(this.eventHandler(this._handle_ngModelChange_42_0.bind(this)));
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_50,'ngModelChange',this.eventHandler(this._handle_ngModelChange_50_0.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_50,'input',this.eventHandler(this._handle_input_50_1.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_50,'blur',this.eventHandler(this._handle_blur_50_2.bind(this)));
    this._expr_55 = import7.UNINITIALIZED;
    this._expr_56 = import7.UNINITIALIZED;
    this._expr_57 = import7.UNINITIALIZED;
    this._expr_58 = import7.UNINITIALIZED;
    const subscription_4:any = this._FormControlName_50_7.update.subscribe(this.eventHandler(this._handle_ngModelChange_50_0.bind(this)));
    this._expr_59 = import7.UNINITIALIZED;
    this._expr_60 = import7.UNINITIALIZED;
    this._expr_61 = import7.UNINITIALIZED;
    this._expr_62 = import7.UNINITIALIZED;
    this._expr_63 = import7.UNINITIALIZED;
    this._expr_64 = import7.UNINITIALIZED;
    var disposable_15:Function = this.renderer.listen(this._el_58,'click',this.eventHandler(this._handle_click_58_0.bind(this)));
    this._expr_66 = import7.UNINITIALIZED;
    this._expr_67 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._el_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    if (((token === import21.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import12.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import21.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import12.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    if (((token === import15.DefaultValueAccessor) && (26 === requestNodeIndex))) { return this._DefaultValueAccessor_26_3; }
    if (((token === import16.RequiredValidator) && (26 === requestNodeIndex))) { return this._RequiredValidator_26_4; }
    if (((token === import26.NG_VALIDATORS) && (26 === requestNodeIndex))) { return this._NG_VALIDATORS_26_5; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_6; }
    if (((token === import17.FormControlName) && (26 === requestNodeIndex))) { return this._FormControlName_26_7; }
    if (((token === import28.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_8; }
    if (((token === import14.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_9; }
    if (((token === import15.DefaultValueAccessor) && (34 === requestNodeIndex))) { return this._DefaultValueAccessor_34_3; }
    if (((token === import16.RequiredValidator) && (34 === requestNodeIndex))) { return this._RequiredValidator_34_4; }
    if (((token === import26.NG_VALIDATORS) && (34 === requestNodeIndex))) { return this._NG_VALIDATORS_34_5; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (34 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_34_6; }
    if (((token === import17.FormControlName) && (34 === requestNodeIndex))) { return this._FormControlName_34_7; }
    if (((token === import28.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_8; }
    if (((token === import14.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_9; }
    if (((token === import15.DefaultValueAccessor) && (42 === requestNodeIndex))) { return this._DefaultValueAccessor_42_3; }
    if (((token === import16.RequiredValidator) && (42 === requestNodeIndex))) { return this._RequiredValidator_42_4; }
    if (((token === import26.NG_VALIDATORS) && (42 === requestNodeIndex))) { return this._NG_VALIDATORS_42_5; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (42 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_42_6; }
    if (((token === import17.FormControlName) && (42 === requestNodeIndex))) { return this._FormControlName_42_7; }
    if (((token === import28.NgControl) && (42 === requestNodeIndex))) { return this._NgControl_42_8; }
    if (((token === import14.NgControlStatus) && (42 === requestNodeIndex))) { return this._NgControlStatus_42_9; }
    if (((token === import15.DefaultValueAccessor) && (50 === requestNodeIndex))) { return this._DefaultValueAccessor_50_3; }
    if (((token === import16.RequiredValidator) && (50 === requestNodeIndex))) { return this._RequiredValidator_50_4; }
    if (((token === import26.NG_VALIDATORS) && (50 === requestNodeIndex))) { return this._NG_VALIDATORS_50_5; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (50 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_50_6; }
    if (((token === import17.FormControlName) && (50 === requestNodeIndex))) { return this._FormControlName_50_7; }
    if (((token === import28.NgControl) && (50 === requestNodeIndex))) { return this._NgControl_50_8; }
    if (((token === import14.NgControlStatus) && (50 === requestNodeIndex))) { return this._NgControlStatus_50_9; }
    if (((token === import18.RouterLinkWithHref) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._RouterLinkWithHref_58_3; }
    if (((token === import13.FormGroupDirective) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._FormGroupDirective_19_3; }
    if (((token === import29.ControlContainer) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._ControlContainer_19_4; }
    if (((token === import14.NgControlStatusGroup) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._NgControlStatusGroup_19_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeaderComponent_0_4.ngOnInit(); }
    const currVal_1:any = this.context.errFlag;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_4_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.successFlag;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_6_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    changes = (null as any);
    const currVal_6:any = this.context.editProfileForm;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._FormGroupDirective_19_3.form = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_19_3.ngOnChanges(changes); }
    const currVal_16:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._RequiredValidator_26_4.required = currVal_16;
      this._expr_16 = currVal_16;
    }
    changes = (null as any);
    const currVal_18:any = 'firstName';
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._FormControlName_26_7.name = currVal_18;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_18,currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this.context.firstName;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._FormControlName_26_7.model = currVal_19;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_19,currVal_19);
      this._expr_19 = currVal_19;
    }
    if ((changes !== (null as any))) { this._FormControlName_26_7.ngOnChanges(changes); }
    const currVal_29:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this._RequiredValidator_34_4.required = currVal_29;
      this._expr_29 = currVal_29;
    }
    changes = (null as any);
    const currVal_31:any = 'lastName';
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._FormControlName_34_7.name = currVal_31;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_31,currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this.context.lastName;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._FormControlName_34_7.model = currVal_32;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_32,currVal_32);
      this._expr_32 = currVal_32;
    }
    if ((changes !== (null as any))) { this._FormControlName_34_7.ngOnChanges(changes); }
    const currVal_42:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this._RequiredValidator_42_4.required = currVal_42;
      this._expr_42 = currVal_42;
    }
    changes = (null as any);
    const currVal_44:any = 'username';
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this._FormControlName_42_7.name = currVal_44;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_44,currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this.context.username;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this._FormControlName_42_7.model = currVal_45;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_45,currVal_45);
      this._expr_45 = currVal_45;
    }
    if ((changes !== (null as any))) { this._FormControlName_42_7.ngOnChanges(changes); }
    const currVal_55:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this._RequiredValidator_50_4.required = currVal_55;
      this._expr_55 = currVal_55;
    }
    changes = (null as any);
    const currVal_57:any = 'mobile';
    if (import4.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this._FormControlName_50_7.name = currVal_57;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_57,currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = this.context.mobile;
    if (import4.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this._FormControlName_50_7.model = currVal_58;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_58,currVal_58);
      this._expr_58 = currVal_58;
    }
    if ((changes !== (null as any))) { this._FormControlName_50_7.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_66:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this._RouterLinkWithHref_58_3.routerLink = currVal_66;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_66,currVal_66);
      this._expr_66 = currVal_66;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_58_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:boolean = !this.context.notificationFlag;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_7:any = this._NgControlStatusGroup_19_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_19_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_19_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_19_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_19_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_19_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_17:any = (this._RequiredValidator_26_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementAttribute(this._el_26,'required',((currVal_17 == (null as any))? (null as any): currVal_17.toString()));
      this._expr_17 = currVal_17;
    }
    const currVal_20:any = this._NgControlStatus_26_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_26_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_26_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_26_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_26_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_26_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_30:any = (this._RequiredValidator_34_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementAttribute(this._el_34,'required',((currVal_30 == (null as any))? (null as any): currVal_30.toString()));
      this._expr_30 = currVal_30;
    }
    const currVal_33:any = this._NgControlStatus_34_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_34,'ng-untouched',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_34_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_34,'ng-touched',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_34_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_34,'ng-pristine',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_34_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_34,'ng-dirty',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_34_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_34,'ng-valid',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_34_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_34,'ng-invalid',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_43:any = (this._RequiredValidator_42_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementAttribute(this._el_42,'required',((currVal_43 == (null as any))? (null as any): currVal_43.toString()));
      this._expr_43 = currVal_43;
    }
    const currVal_46:any = this._NgControlStatus_42_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_42,'ng-untouched',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_42_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_42,'ng-touched',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_42_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_42,'ng-pristine',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_42_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_42,'ng-dirty',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = this._NgControlStatus_42_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_42,'ng-valid',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_42_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_42,'ng-invalid',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_56:any = (this._RequiredValidator_50_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementAttribute(this._el_50,'required',((currVal_56 == (null as any))? (null as any): currVal_56.toString()));
      this._expr_56 = currVal_56;
    }
    const currVal_59:any = this._NgControlStatus_50_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementClass(this._el_50,'ng-untouched',currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_60:any = this._NgControlStatus_50_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementClass(this._el_50,'ng-touched',currVal_60);
      this._expr_60 = currVal_60;
    }
    const currVal_61:any = this._NgControlStatus_50_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setElementClass(this._el_50,'ng-pristine',currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_62:any = this._NgControlStatus_50_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setElementClass(this._el_50,'ng-dirty',currVal_62);
      this._expr_62 = currVal_62;
    }
    const currVal_63:any = this._NgControlStatus_50_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this.renderer.setElementClass(this._el_50,'ng-valid',currVal_63);
      this._expr_63 = currVal_63;
    }
    const currVal_64:any = this._NgControlStatus_50_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setElementClass(this._el_50,'ng-invalid',currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_67:any = this._RouterLinkWithHref_58_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_67,currVal_67)) {
      this.renderer.setElementProperty(this._el_58,'href',this.viewUtils.sanitizer.sanitize(import30.SecurityContext.URL,currVal_67));
      this._expr_67 = currVal_67;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_26_7.ngOnDestroy();
    this._FormControlName_34_7.ngOnDestroy();
    this._FormControlName_42_7.ngOnDestroy();
    this._FormControlName_50_7.ngOnDestroy();
    this._RouterLinkWithHref_58_3.ngOnDestroy();
  }
  private _handle_ngSubmit_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSave()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_19_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_19_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_19_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_19_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.firstName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_26_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_26_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_26_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_26_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.lastName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_34_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_34_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.username = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_42_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_42_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_42_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_42_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_50_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.mobile = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_50_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_50_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_50_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_50_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_58_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_58_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_UserProfileEditComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UserProfileEditComponent> {
  if ((renderType_UserProfileEditComponent === (null as any))) { (renderType_UserProfileEditComponent = viewUtils.createRenderComponentType('/Users/prasadsawant/Sites/fintech_mean/frontend/app/auth/user.profile.edit.component.html',0,import9.ViewEncapsulation.None,styles_UserProfileEditComponent,{})); }
  return new _View_UserProfileEditComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_UserProfileEditComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserProfileEditComponent1,renderType_UserProfileEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger alert-dismissable fade in');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'aria-label','close');
    this.renderer.setElementAttribute(this._el_2,'class','close');
    this.renderer.setElementAttribute(this._el_2,'data-dismiss','alert');
    this.renderer.setElementAttribute(this._el_2,'href','#');
    this._text_3 = this.renderer.createText(this._el_2,'×',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'strong',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Error!',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,' ',this.parent.context.errMessage,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserProfileEditComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserProfileEditComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_UserProfileEditComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserProfileEditComponent2,renderType_UserProfileEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-success alert-dismissable fade in');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'aria-label','close');
    this.renderer.setElementAttribute(this._el_2,'class','close');
    this.renderer.setElementAttribute(this._el_2,'data-dismiss','alert');
    this.renderer.setElementAttribute(this._el_2,'href','#');
    this._text_3 = this.renderer.createText(this._el_2,'×',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'strong',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Success!',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,' ',this.parent.context.successMessage,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserProfileEditComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserProfileEditComponent2(viewUtils,parentInjector,declarationEl);
}