/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './add.new.scheme.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './scheme.service';
import * as import9 from '../error/error.service';
import * as import10 from '../notification/notification.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './add.new.scheme.component.html.shim';
import * as import14 from '../header/header.component';
import * as import15 from '@angular/common/src/directives/ng_if';
import * as import16 from '@angular/forms/src/directives/ng_form';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import19 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import20 from '@angular/common/src/directives/ng_for';
import * as import21 from '@angular/forms/src/directives/default_value_accessor';
import * as import22 from '@angular/forms/src/directives/validators';
import * as import23 from '@angular/forms/src/directives/ng_model';
import * as import24 from '../header/header.component.ngfactory';
import * as import25 from '../auth/auth.service';
import * as import26 from '@angular/core/src/linker/template_ref';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import29 from '@angular/forms/src/validators';
import * as import30 from '@angular/forms/src/directives/control_value_accessor';
import * as import31 from '@angular/forms/src/directives/ng_control';
import * as import32 from '@angular/forms/src/directives/control_container';
var renderType_AddNewSchemeComponent_Host:import0.RenderComponentType = (null as any);
class _View_AddNewSchemeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AddNewSchemeComponent_0_4:import3.AddNewSchemeComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AddNewSchemeComponent_Host0,renderType_AddNewSchemeComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-new-scheme',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AddNewSchemeComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AddNewSchemeComponent_0_4 = new import3.AddNewSchemeComponent(this.parentInjector.get(import8.SchemeService),this.parentInjector.get(import9.ErrorService),this.parentInjector.get(import10.NotificationService));
    this._appEl_0.initComponent(this._AddNewSchemeComponent_0_4,[],compView_0);
    compView_0.create(this._AddNewSchemeComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AddNewSchemeComponent) && (0 === requestNodeIndex))) { return this._AddNewSchemeComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._AddNewSchemeComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AddNewSchemeComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AddNewSchemeComponent_Host === (null as any))) { (renderType_AddNewSchemeComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_AddNewSchemeComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AddNewSchemeComponentNgFactory:import12.ComponentFactory<import3.AddNewSchemeComponent> = new import12.ComponentFactory<import3.AddNewSchemeComponent>('app-new-scheme',viewFactory_AddNewSchemeComponent_Host0,import3.AddNewSchemeComponent);
const styles_AddNewSchemeComponent:any[] = [import13.styles];
var renderType_AddNewSchemeComponent:import0.RenderComponentType = (null as any);
class _View_AddNewSchemeComponent0 extends import1.AppView<import3.AddNewSchemeComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import14.HeaderComponent;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import15.NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _NgForm_6_3:import16.NgForm;
  _ControlContainer_6_4:any;
  _NgControlStatusGroup_6_5:import17.NgControlStatusGroup;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _NgSelectOption_18_3:import18.NgSelectOption;
  _NgSelectMultipleOption_18_4:import19.NgSelectMultipleOption;
  _text_19:any;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _TemplateRef_21_5:any;
  _NgFor_21_6:import20.NgFor;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _DefaultValueAccessor_30_3:import21.DefaultValueAccessor;
  _RequiredValidator_30_4:import22.RequiredValidator;
  _NG_VALIDATORS_30_5:any[];
  _NG_VALUE_ACCESSOR_30_6:any[];
  _NgModel_30_7:import23.NgModel;
  _NgControl_30_8:any;
  _NgControlStatus_30_9:import17.NgControlStatus;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _DefaultValueAccessor_38_3:import21.DefaultValueAccessor;
  _RequiredValidator_38_4:import22.RequiredValidator;
  _NG_VALIDATORS_38_5:any[];
  _NG_VALUE_ACCESSOR_38_6:any[];
  _NgModel_38_7:import23.NgModel;
  _NgControl_38_8:any;
  _NgControlStatus_38_9:import17.NgControlStatus;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AddNewSchemeComponent0,renderType_AddNewSchemeComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'app-header',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import24.viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import14.HeaderComponent(this.parentInjector.get(import25.AuthService));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,[],(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_2 = new import2.AppElement(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import26.TemplateRef_(this._appEl_2,viewFactory_AddNewSchemeComponent1);
    this._NgIf_2_6 = new import15.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_4 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','row col-md-6 col-md-offset-3');
    this._text_5 = this.renderer.createText(this._el_4,'\n     ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'form',(null as any));
    this._NgForm_6_3 = new import16.NgForm((null as any),(null as any));
    this._ControlContainer_6_4 = this._NgForm_6_3;
    this._NgControlStatusGroup_6_5 = new import17.NgControlStatusGroup(this._ControlContainer_6_4);
    this._text_7 = this.renderer.createText(this._el_6,'\n         ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'h2',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Add New Scheme',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n\n         ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','form-group');
    this._text_12 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'label',(null as any));
    this.renderer.setElementAttribute(this._el_13,'for','sel1');
    this._text_14 = this.renderer.createText(this._el_13,'Ledger Nature:',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_11,'select',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','form-control');
    this.renderer.setElementAttribute(this._el_16,'id','sel1');
    this.renderer.setElementAttribute(this._el_16,'name','ledgerNature');
    this._text_17 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'option',(null as any));
    this.renderer.setElementAttribute(this._el_18,'selected','true');
    this._NgSelectOption_18_3 = new import18.NgSelectOption(new import27.ElementRef(this._el_18),this.renderer,(null as any));
    this._NgSelectMultipleOption_18_4 = new import19.NgSelectMultipleOption(new import27.ElementRef(this._el_18),this.renderer,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Select Ledger Type',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._appEl_21 = new import2.AppElement(21,16,this,this._anchor_21);
    this._TemplateRef_21_5 = new import26.TemplateRef_(this._appEl_21,viewFactory_AddNewSchemeComponent2);
    this._NgFor_21_6 = new import20.NgFor(this._appEl_21.vcRef,this._TemplateRef_21_5,this.parentInjector.get(import28.IterableDiffers),this.ref);
    this._text_22 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_6,'\n\n         ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','form-group');
    this._text_26 = this.renderer.createText(this._el_25,'\n             ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'label',(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Ledger Name:',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n             ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_25,'input',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','form-control');
    this.renderer.setElementAttribute(this._el_30,'name','ledgerName');
    this.renderer.setElementAttribute(this._el_30,'ngModel','');
    this.renderer.setElementAttribute(this._el_30,'placeholder','Enter Ledger Name');
    this.renderer.setElementAttribute(this._el_30,'required','true');
    this.renderer.setElementAttribute(this._el_30,'type','text');
    this._DefaultValueAccessor_30_3 = new import21.DefaultValueAccessor(this.renderer,new import27.ElementRef(this._el_30));
    this._RequiredValidator_30_4 = new import22.RequiredValidator();
    this._NG_VALIDATORS_30_5 = [this._RequiredValidator_30_4];
    this._NG_VALUE_ACCESSOR_30_6 = [this._DefaultValueAccessor_30_3];
    this._NgModel_30_7 = new import23.NgModel(this._ControlContainer_6_4,this._NG_VALIDATORS_30_5,(null as any),this._NG_VALUE_ACCESSOR_30_6);
    this._NgControl_30_8 = this._NgModel_30_7;
    this._NgControlStatus_30_9 = new import17.NgControlStatus(this._NgControl_30_8);
    this._text_31 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','form-group');
    this._text_34 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'label',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'Ledger Type:',(null as any));
    this._text_37 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_33,'input',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','form-control');
    this.renderer.setElementAttribute(this._el_38,'name','ledgerType');
    this.renderer.setElementAttribute(this._el_38,'ngModel','');
    this.renderer.setElementAttribute(this._el_38,'placeholder','Enter Ledger Type');
    this.renderer.setElementAttribute(this._el_38,'readonly','');
    this.renderer.setElementAttribute(this._el_38,'required','true');
    this.renderer.setElementAttribute(this._el_38,'type','text');
    this._DefaultValueAccessor_38_3 = new import21.DefaultValueAccessor(this.renderer,new import27.ElementRef(this._el_38));
    this._RequiredValidator_38_4 = new import22.RequiredValidator();
    this._NG_VALIDATORS_38_5 = [this._RequiredValidator_38_4];
    this._NG_VALUE_ACCESSOR_38_6 = [this._DefaultValueAccessor_38_3];
    this._NgModel_38_7 = new import23.NgModel(this._ControlContainer_6_4,this._NG_VALIDATORS_38_5,(null as any),this._NG_VALUE_ACCESSOR_38_6);
    this._NgControl_38_8 = this._NgModel_38_7;
    this._NgControlStatus_38_9 = new import17.NgControlStatus(this._NgControl_38_8);
    this._text_39 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_6,'hr',(null as any));
    this._text_42 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_6,'button',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','btn btn-success btn-lg');
    this.renderer.setElementAttribute(this._el_43,'type','submit');
    this._text_44 = this.renderer.createText(this._el_43,'Save',(null as any));
    this._text_45 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_46 = this.renderer.createText(this._el_4,'    \n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_6,'ngSubmit',this.eventHandler(this._handle_ngSubmit_6_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_6,'submit',this.eventHandler(this._handle_submit_6_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_6,'reset',this.eventHandler(this._handle_reset_6_2.bind(this)));
    const subscription_0:any = this._NgForm_6_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_6_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_16,'change',this.eventHandler(this._handle_change_16_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_30,'input',this.eventHandler(this._handle_input_30_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_30,'blur',this.eventHandler(this._handle_blur_30_1.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_38,'ngModelChange',this.eventHandler(this._handle_ngModelChange_38_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_38,'input',this.eventHandler(this._handle_input_38_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_38,'blur',this.eventHandler(this._handle_blur_38_2.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_38_7.update.subscribe(this.eventHandler(this._handle_ngModelChange_38_0.bind(this)));
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    if (((token === import26.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import15.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import18.NgSelectOption) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgSelectOption_18_3; }
    if (((token === import19.NgSelectMultipleOption) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgSelectMultipleOption_18_4; }
    if (((token === import26.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import20.NgFor) && (21 === requestNodeIndex))) { return this._NgFor_21_6; }
    if (((token === import21.DefaultValueAccessor) && (30 === requestNodeIndex))) { return this._DefaultValueAccessor_30_3; }
    if (((token === import22.RequiredValidator) && (30 === requestNodeIndex))) { return this._RequiredValidator_30_4; }
    if (((token === import29.NG_VALIDATORS) && (30 === requestNodeIndex))) { return this._NG_VALIDATORS_30_5; }
    if (((token === import30.NG_VALUE_ACCESSOR) && (30 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_30_6; }
    if (((token === import23.NgModel) && (30 === requestNodeIndex))) { return this._NgModel_30_7; }
    if (((token === import31.NgControl) && (30 === requestNodeIndex))) { return this._NgControl_30_8; }
    if (((token === import17.NgControlStatus) && (30 === requestNodeIndex))) { return this._NgControlStatus_30_9; }
    if (((token === import21.DefaultValueAccessor) && (38 === requestNodeIndex))) { return this._DefaultValueAccessor_38_3; }
    if (((token === import22.RequiredValidator) && (38 === requestNodeIndex))) { return this._RequiredValidator_38_4; }
    if (((token === import29.NG_VALIDATORS) && (38 === requestNodeIndex))) { return this._NG_VALIDATORS_38_5; }
    if (((token === import30.NG_VALUE_ACCESSOR) && (38 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_38_6; }
    if (((token === import23.NgModel) && (38 === requestNodeIndex))) { return this._NgModel_38_7; }
    if (((token === import31.NgControl) && (38 === requestNodeIndex))) { return this._NgControl_38_8; }
    if (((token === import17.NgControlStatus) && (38 === requestNodeIndex))) { return this._NgControlStatus_38_9; }
    if (((token === import16.NgForm) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._NgForm_6_3; }
    if (((token === import32.ControlContainer) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._ControlContainer_6_4; }
    if (((token === import17.NgControlStatusGroup) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._NgControlStatusGroup_6_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeaderComponent_0_4.ngOnInit(); }
    const currVal_0:any = this.context.loading;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    changes = (null as any);
    const currVal_13:any = this.context.ledgers;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgFor_21_6.ngForOf = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._NgFor_21_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_21_6.ngDoCheck(); }
    const currVal_16:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._RequiredValidator_30_4.required = currVal_16;
      this._expr_16 = currVal_16;
    }
    changes = (null as any);
    const currVal_18:any = 'ledgerName';
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._NgModel_30_7.name = currVal_18;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_18,currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._NgModel_30_7.model = currVal_19;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_19,currVal_19);
      this._expr_19 = currVal_19;
    }
    if ((changes !== (null as any))) { this._NgModel_30_7.ngOnChanges(changes); }
    const currVal_29:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this._RequiredValidator_38_4.required = currVal_29;
      this._expr_29 = currVal_29;
    }
    changes = (null as any);
    const currVal_31:any = 'ledgerType';
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._NgModel_38_7.name = currVal_31;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_31,currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this.context.nature;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._NgModel_38_7.model = currVal_32;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_32,currVal_32);
      this._expr_32 = currVal_32;
    }
    if ((changes !== (null as any))) { this._NgModel_38_7.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_6_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_6,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_6_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_6,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_6_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_6_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_6,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_6_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_6,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_6_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_6,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_17:any = (this._RequiredValidator_30_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementAttribute(this._el_30,'required',((currVal_17 == (null as any))? (null as any): currVal_17.toString()));
      this._expr_17 = currVal_17;
    }
    const currVal_20:any = this._NgControlStatus_30_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_30,'ng-untouched',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_30_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_30,'ng-touched',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_30_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_30,'ng-pristine',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_30_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_30,'ng-dirty',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_30_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_30,'ng-valid',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_30_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_30,'ng-invalid',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_30:any = (this._RequiredValidator_38_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementAttribute(this._el_38,'required',((currVal_30 == (null as any))? (null as any): currVal_30.toString()));
      this._expr_30 = currVal_30;
    }
    const currVal_33:any = this._NgControlStatus_38_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_38,'ng-untouched',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_38_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_38,'ng-touched',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_38_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_38,'ng-pristine',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_38_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_38,'ng-dirty',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_38_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_38,'ng-valid',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_38_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_38,'ng-invalid',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgForm_6_3.form.invalid;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementProperty(this._el_43,'disabled',currVal_39);
      this._expr_39 = currVal_39;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgSelectOption_18_3.ngOnDestroy();
    this._NgSelectMultipleOption_18_4.ngOnDestroy();
    this._NgModel_30_7.ngOnDestroy();
    this._NgModel_38_7.ngOnDestroy();
  }
  private _handle_ngSubmit_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSave(this._NgForm_6_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_6_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_6_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_6_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_6_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_change_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_input_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_30_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_30_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_30_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_38_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.nature = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_38_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_38_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_38_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_38_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AddNewSchemeComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AddNewSchemeComponent> {
  if ((renderType_AddNewSchemeComponent === (null as any))) { (renderType_AddNewSchemeComponent = viewUtils.createRenderComponentType('/Users/prasadsawant/Sites/fintech_mean/frontend/app/scheme/add.new.scheme.component.html',0,import11.ViewEncapsulation.Emulated,styles_AddNewSchemeComponent,{})); }
  return new _View_AddNewSchemeComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_AddNewSchemeComponent1 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AddNewSchemeComponent1,renderType_AddNewSchemeComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','loading');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_AddNewSchemeComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AddNewSchemeComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_AddNewSchemeComponent2 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import18.NgSelectOption;
  _NgSelectMultipleOption_0_4:import19.NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AddNewSchemeComponent2,renderType_AddNewSchemeComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'option',(null as any));
    this._NgSelectOption_0_3 = new import18.NgSelectOption(new import27.ElementRef(this._el_0),this.renderer,(null as any));
    this._NgSelectMultipleOption_0_4 = new import19.NgSelectMultipleOption(new import27.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3; }
    if (((token === import19.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit.name;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgSelectOption_0_3.value = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.$implicit.name;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgSelectMultipleOption_0_4.value = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
}
function viewFactory_AddNewSchemeComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AddNewSchemeComponent2(viewUtils,parentInjector,declarationEl);
}