/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['div.row[_ngcontent-%COMP%] {\n    margin-bottom: 20px;\n}\n\n\n.overlay[_ngcontent-%COMP%]{\n    margin-left: -3%;\n    margin-top:-20px;\n    z-index:100;\n    width:103%;\n    height: 102%;\n    position:absolute;\n    display: block;\n    background-color: rgba(0,0,0, 0.6);\n}'];