/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['div.row[_ngcontent-%COMP%] {\n    margin-bottom: 20px;\n}\n\nform[_ngcontent-%COMP%]   button[type="submit"][_ngcontent-%COMP%] {\n    \n}'];