/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './list.member.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './member.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './list.member.component.css.shim';
import * as import12 from '../app.component.css.shim';
import * as import13 from '../header/header.component';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '@angular/forms/src/directives/ng_form';
import * as import16 from '@angular/forms/src/directives/ng_control_status';
import * as import17 from '@angular/forms/src/directives/default_value_accessor';
import * as import18 from '@angular/forms/src/directives/validators';
import * as import19 from '@angular/forms/src/directives/ng_model';
import * as import20 from '@angular/router/src/directives/router_link';
import * as import21 from '../header/header.component.ngfactory';
import * as import22 from '../auth/auth.service';
import * as import23 from '@angular/core/src/linker/template_ref';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from '@angular/router/src/router';
import * as import26 from '@angular/router/src/router_state';
import * as import27 from '@angular/common/src/location/location_strategy';
import * as import28 from '@angular/forms/src/validators';
import * as import29 from '@angular/forms/src/directives/control_value_accessor';
import * as import30 from '@angular/forms/src/directives/ng_control';
import * as import31 from '@angular/forms/src/directives/control_container';
import * as import32 from '@angular/core/src/security';
import * as import33 from '@angular/common/src/directives/ng_for';
import * as import34 from '@angular/core/src/change_detection/differs/iterable_differs';
var renderType_ListMemberComponent_Host:import0.RenderComponentType = (null as any);
class _View_ListMemberComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ListMemberComponent_0_4:import3.ListMemberComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ListMemberComponent_Host0,renderType_ListMemberComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-list-member',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ListMemberComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ListMemberComponent_0_4 = new import3.ListMemberComponent(this.parentInjector.get(import8.MemberService));
    this._appEl_0.initComponent(this._ListMemberComponent_0_4,[],compView_0);
    compView_0.create(this._ListMemberComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ListMemberComponent) && (0 === requestNodeIndex))) { return this._ListMemberComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ListMemberComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ListMemberComponent_Host === (null as any))) { (renderType_ListMemberComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ListMemberComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ListMemberComponentNgFactory:import10.ComponentFactory<import3.ListMemberComponent> = new import10.ComponentFactory<import3.ListMemberComponent>('app-list-member',viewFactory_ListMemberComponent_Host0,import3.ListMemberComponent);
const styles_ListMemberComponent:any[] = [
  import11.styles,
  import12.styles
]
;
var renderType_ListMemberComponent:import0.RenderComponentType = (null as any);
class _View_ListMemberComponent0 extends import1.AppView<import3.ListMemberComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import13.HeaderComponent;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import14.NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _NgForm_8_3:import15.NgForm;
  _ControlContainer_8_4:any;
  _NgControlStatusGroup_8_5:import16.NgControlStatusGroup;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _DefaultValueAccessor_20_3:import17.DefaultValueAccessor;
  _RequiredValidator_20_4:import18.RequiredValidator;
  _NG_VALIDATORS_20_5:any[];
  _NG_VALUE_ACCESSOR_20_6:any[];
  _NgModel_20_7:import19.NgModel;
  _NgControl_20_8:any;
  _NgControlStatus_20_9:import16.NgControlStatus;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _DefaultValueAccessor_28_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_28_4:any[];
  _NgModel_28_5:import19.NgModel;
  _NgControl_28_6:any;
  _NgControlStatus_28_7:import16.NgControlStatus;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _RouterLinkWithHref_36_3:import20.RouterLinkWithHref;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _el_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _anchor_49:any;
  /*private*/ _appEl_49:import2.AppElement;
  _TemplateRef_49_5:any;
  _NgIf_49_6:import14.NgIf;
  _text_50:any;
  _anchor_51:any;
  /*private*/ _appEl_51:import2.AppElement;
  _TemplateRef_51_5:any;
  _NgIf_51_6:import14.NgIf;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _el_55:any;
  _el_56:any;
  _text_57:any;
  _anchor_58:any;
  /*private*/ _appEl_58:import2.AppElement;
  _TemplateRef_58_5:any;
  _NgIf_58_6:import14.NgIf;
  _text_59:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ListMemberComponent0,renderType_ListMemberComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'app-header',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import13.HeaderComponent(this.parentInjector.get(import22.AuthService));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,[],(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_2 = new import2.AppElement(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import23.TemplateRef_(this._appEl_2,viewFactory_ListMemberComponent1);
    this._NgIf_2_6 = new import14.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_4 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','row');
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','col-md-6 col-md-offset-3');
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'form',(null as any));
    this._NgForm_8_3 = new import15.NgForm((null as any),(null as any));
    this._ControlContainer_8_4 = this._NgForm_8_3;
    this._NgControlStatusGroup_8_5 = new import16.NgControlStatusGroup(this._ControlContainer_8_4);
    this._text_9 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','col-md-12');
    this._text_11 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'h2',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Search Member',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','form-group');
    this._text_16 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'label',(null as any));
    this.renderer.setElementAttribute(this._el_17,'for','lastName');
    this._text_18 = this.renderer.createText(this._el_17,'Last Name:',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_15,'input',(null as any));
    this.renderer.setElementAttribute(this._el_20,'autocomplete','off');
    this.renderer.setElementAttribute(this._el_20,'class','form-control input-lg');
    this.renderer.setElementAttribute(this._el_20,'name','lastName');
    this.renderer.setElementAttribute(this._el_20,'ngModel','');
    this.renderer.setElementAttribute(this._el_20,'placeholder','Enter Last Name');
    this.renderer.setElementAttribute(this._el_20,'required','true');
    this.renderer.setElementAttribute(this._el_20,'type','text');
    this._DefaultValueAccessor_20_3 = new import17.DefaultValueAccessor(this.renderer,new import24.ElementRef(this._el_20));
    this._RequiredValidator_20_4 = new import18.RequiredValidator();
    this._NG_VALIDATORS_20_5 = [this._RequiredValidator_20_4];
    this._NG_VALUE_ACCESSOR_20_6 = [this._DefaultValueAccessor_20_3];
    this._NgModel_20_7 = new import19.NgModel(this._ControlContainer_8_4,this._NG_VALIDATORS_20_5,(null as any),this._NG_VALUE_ACCESSOR_20_6);
    this._NgControl_20_8 = this._NgModel_20_7;
    this._NgControlStatus_20_9 = new import16.NgControlStatus(this._NgControl_20_8);
    this._text_21 = this.renderer.createText(this._el_15,'                    \n                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','form-group');
    this._text_24 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'label',(null as any));
    this.renderer.setElementAttribute(this._el_25,'for','query');
    this._text_26 = this.renderer.createText(this._el_25,'Mobile Number or Aadhar Number or Pan Number:',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n                    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_23,'input',(null as any));
    this.renderer.setElementAttribute(this._el_28,'autocomplete','off');
    this.renderer.setElementAttribute(this._el_28,'class','form-control input-lg');
    this.renderer.setElementAttribute(this._el_28,'name','query');
    this.renderer.setElementAttribute(this._el_28,'ngModel','');
    this.renderer.setElementAttribute(this._el_28,'placeholder','Enter Mobile Number or Aadhar Number or Pan Number');
    this.renderer.setElementAttribute(this._el_28,'type','text');
    this._DefaultValueAccessor_28_3 = new import17.DefaultValueAccessor(this.renderer,new import24.ElementRef(this._el_28));
    this._NG_VALUE_ACCESSOR_28_4 = [this._DefaultValueAccessor_28_3];
    this._NgModel_28_5 = new import19.NgModel(this._ControlContainer_8_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_28_4);
    this._NgControl_28_6 = this._NgModel_28_5;
    this._NgControlStatus_28_7 = new import16.NgControlStatus(this._NgControl_28_6);
    this._text_29 = this.renderer.createText(this._el_23,'                    \n                ',(null as any));
    this._text_30 = this.renderer.createText(this._el_10,'\n\n                ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_10,'hr',(null as any));
    this._text_32 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','btn btn-info btn-lg');
    this.renderer.setElementAttribute(this._el_33,'type','submit');
    this._text_34 = this.renderer.createText(this._el_33,'Search',(null as any));
    this._text_35 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_10,'a',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','btn btn-default btn-lg');
    this.renderer.setElementAttribute(this._el_36,'routerLink','/');
    this._RouterLinkWithHref_36_3 = new import20.RouterLinkWithHref(this.parentInjector.get(import25.Router),this.parentInjector.get(import26.ActivatedRoute),this.parentInjector.get(import27.LocationStrategy));
    this._text_37 = this.renderer.createText(this._el_36,'Cancel',(null as any));
    this._text_38 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._text_39 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_41 = this.renderer.createText(this._el_4,'\n',(null as any));
    this._text_42 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_43 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_44 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_45 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_46 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_47 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','col-sm-6 col-sm-offset-3');
    this._text_48 = this.renderer.createText(this._el_47,'\n    ',(null as any));
    this._anchor_49 = this.renderer.createTemplateAnchor(this._el_47,(null as any));
    this._appEl_49 = new import2.AppElement(49,47,this,this._anchor_49);
    this._TemplateRef_49_5 = new import23.TemplateRef_(this._appEl_49,viewFactory_ListMemberComponent2);
    this._NgIf_49_6 = new import14.NgIf(this._appEl_49.vcRef,this._TemplateRef_49_5);
    this._text_50 = this.renderer.createText(this._el_47,'\n\n    ',(null as any));
    this._anchor_51 = this.renderer.createTemplateAnchor(this._el_47,(null as any));
    this._appEl_51 = new import2.AppElement(51,47,this,this._anchor_51);
    this._TemplateRef_51_5 = new import23.TemplateRef_(this._appEl_51,viewFactory_ListMemberComponent3);
    this._NgIf_51_6 = new import14.NgIf(this._appEl_51.vcRef,this._TemplateRef_51_5);
    this._text_52 = this.renderer.createText(this._el_47,'\n',(null as any));
    this._text_53 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_54 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_55 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._el_56 = this.renderer.createElement(parentRenderNode,'br',(null as any));
    this._text_57 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_58 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_58 = new import2.AppElement(58,(null as any),this,this._anchor_58);
    this._TemplateRef_58_5 = new import23.TemplateRef_(this._appEl_58,viewFactory_ListMemberComponent4);
    this._NgIf_58_6 = new import14.NgIf(this._appEl_58.vcRef,this._TemplateRef_58_5);
    this._text_59 = this.renderer.createText(parentRenderNode,'\n\n\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_8,'ngSubmit',this.eventHandler(this._handle_ngSubmit_8_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_8,'submit',this.eventHandler(this._handle_submit_8_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_8,'reset',this.eventHandler(this._handle_reset_8_2.bind(this)));
    const subscription_0:any = this._NgForm_8_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_8_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_20,'input',this.eventHandler(this._handle_input_20_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_20,'blur',this.eventHandler(this._handle_blur_20_1.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_28,'input',this.eventHandler(this._handle_input_28_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_28,'blur',this.eventHandler(this._handle_blur_28_1.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_36,'click',this.eventHandler(this._handle_click_36_0.bind(this)));
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._el_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._anchor_49,
      this._text_50,
      this._anchor_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._el_55,
      this._el_56,
      this._text_57,
      this._anchor_58,
      this._text_59
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    if (((token === import23.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import14.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    if (((token === import17.DefaultValueAccessor) && (20 === requestNodeIndex))) { return this._DefaultValueAccessor_20_3; }
    if (((token === import18.RequiredValidator) && (20 === requestNodeIndex))) { return this._RequiredValidator_20_4; }
    if (((token === import28.NG_VALIDATORS) && (20 === requestNodeIndex))) { return this._NG_VALIDATORS_20_5; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (20 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_20_6; }
    if (((token === import19.NgModel) && (20 === requestNodeIndex))) { return this._NgModel_20_7; }
    if (((token === import30.NgControl) && (20 === requestNodeIndex))) { return this._NgControl_20_8; }
    if (((token === import16.NgControlStatus) && (20 === requestNodeIndex))) { return this._NgControlStatus_20_9; }
    if (((token === import17.DefaultValueAccessor) && (28 === requestNodeIndex))) { return this._DefaultValueAccessor_28_3; }
    if (((token === import29.NG_VALUE_ACCESSOR) && (28 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_28_4; }
    if (((token === import19.NgModel) && (28 === requestNodeIndex))) { return this._NgModel_28_5; }
    if (((token === import30.NgControl) && (28 === requestNodeIndex))) { return this._NgControl_28_6; }
    if (((token === import16.NgControlStatus) && (28 === requestNodeIndex))) { return this._NgControlStatus_28_7; }
    if (((token === import20.RouterLinkWithHref) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._RouterLinkWithHref_36_3; }
    if (((token === import15.NgForm) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._NgForm_8_3; }
    if (((token === import31.ControlContainer) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ControlContainer_8_4; }
    if (((token === import16.NgControlStatusGroup) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._NgControlStatusGroup_8_5; }
    if (((token === import23.TemplateRef) && (49 === requestNodeIndex))) { return this._TemplateRef_49_5; }
    if (((token === import14.NgIf) && (49 === requestNodeIndex))) { return this._NgIf_49_6; }
    if (((token === import23.TemplateRef) && (51 === requestNodeIndex))) { return this._TemplateRef_51_5; }
    if (((token === import14.NgIf) && (51 === requestNodeIndex))) { return this._NgIf_51_6; }
    if (((token === import23.TemplateRef) && (58 === requestNodeIndex))) { return this._TemplateRef_58_5; }
    if (((token === import14.NgIf) && (58 === requestNodeIndex))) { return this._NgIf_58_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeaderComponent_0_4.ngOnInit(); }
    const currVal_0:any = this.context.loading;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_12:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._RequiredValidator_20_4.required = currVal_12;
      this._expr_12 = currVal_12;
    }
    changes = (null as any);
    const currVal_14:any = 'lastName';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_20_7.name = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.context.loading;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgModel_20_7.isDisabled = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['isDisabled'] = new import7.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._NgModel_20_7.model = currVal_16;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_16,currVal_16);
      this._expr_16 = currVal_16;
    }
    if ((changes !== (null as any))) { this._NgModel_20_7.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_25:any = 'query';
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._NgModel_28_5.name = currVal_25;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_25,currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this.context.loading;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._NgModel_28_5.isDisabled = currVal_26;
      if ((changes === (null as any))) { (changes = {}); }
      changes['isDisabled'] = new import7.SimpleChange(this._expr_26,currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._NgModel_28_5.model = currVal_27;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_27,currVal_27);
      this._expr_27 = currVal_27;
    }
    if ((changes !== (null as any))) { this._NgModel_28_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_36:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this._RouterLinkWithHref_36_3.routerLink = currVal_36;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_36,currVal_36);
      this._expr_36 = currVal_36;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_36_3.ngOnChanges(changes); }
    const currVal_39:any = this.context.errFlag;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this._NgIf_49_6.ngIf = currVal_39;
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this.context.successFlag;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this._NgIf_51_6.ngIf = currVal_40;
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this.context.successFlag;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this._NgIf_58_6.ngIf = currVal_41;
      this._expr_41 = currVal_41;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_8_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_8,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_8_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_8,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_8_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_8,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_8_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_8,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_8_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_8,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_8_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_8,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = (this._RequiredValidator_20_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_20,'required',((currVal_13 == (null as any))? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    const currVal_17:any = this._NgControlStatus_20_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_20_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_20_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_20_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_20_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_20_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_28:any = this._NgControlStatus_28_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_28,'ng-untouched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_28_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_28,'ng-touched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_28_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_28,'ng-pristine',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_28_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_28,'ng-dirty',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_28_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_28,'ng-valid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_28_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_28,'ng-invalid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this.context.loading;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementProperty(this._el_33,'disabled',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_37:any = this._RouterLinkWithHref_36_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementProperty(this._el_36,'href',this.viewUtils.sanitizer.sanitize(import32.SecurityContext.URL,currVal_37));
      this._expr_37 = currVal_37;
    }
    const currVal_38:boolean = !this.context.notificationFlag;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementProperty(this._el_47,'hidden',currVal_38);
      this._expr_38 = currVal_38;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_20_7.ngOnDestroy();
    this._NgModel_28_5.ngOnDestroy();
    this._RouterLinkWithHref_36_3.ngOnDestroy();
  }
  private _handle_ngSubmit_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSearch(this._NgForm_8_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_8_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_8_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_8_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_8_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_20_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_20_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_20_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_28_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_28_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_28_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_36_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_36_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ListMemberComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ListMemberComponent> {
  if ((renderType_ListMemberComponent === (null as any))) { (renderType_ListMemberComponent = viewUtils.createRenderComponentType('/Users/prasadsawant/Sites/fintech_mean/frontend/app/member/list.member.component.html',0,import9.ViewEncapsulation.Emulated,styles_ListMemberComponent,{})); }
  return new _View_ListMemberComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ListMemberComponent1 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ListMemberComponent1,renderType_ListMemberComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','loading');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_ListMemberComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ListMemberComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ListMemberComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ListMemberComponent2,renderType_ListMemberComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-danger alert-dismissable fade in');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'aria-label','close');
    this.renderer.setElementAttribute(this._el_2,'class','close');
    this.renderer.setElementAttribute(this._el_2,'data-dismiss','alert');
    this.renderer.setElementAttribute(this._el_2,'href','#');
    this._text_3 = this.renderer.createText(this._el_2,'×',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'strong',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Error!',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,' ',this.parent.context.errMessage,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ListMemberComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ListMemberComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ListMemberComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ListMemberComponent3,renderType_ListMemberComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','alert alert-success alert-dismissable fade in');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'aria-label','close');
    this.renderer.setElementAttribute(this._el_2,'class','close');
    this.renderer.setElementAttribute(this._el_2,'data-dismiss','alert');
    this.renderer.setElementAttribute(this._el_2,'href','#');
    this._text_3 = this.renderer.createText(this._el_2,'×',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'strong',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Success!',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,' ',this.parent.context.successMessage,'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ListMemberComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ListMemberComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_ListMemberComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _TemplateRef_32_5:any;
  _NgFor_32_6:import33.NgFor;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ListMemberComponent4,renderType_ListMemberComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-12');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'table',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','table table-responsive table-hover table-bordered');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'thead',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'tr',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'td',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'First Name',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_6,'td',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Last Name',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_6,'td',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Member ID',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_6,'td',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Mobile',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_6,'td',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Email',(null as any));
    this._text_22 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_6,'td',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Address',(null as any));
    this._text_25 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_6,'td',(null as any));
    this._text_27 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_29 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_2,'tbody',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n            ',(null as any));
    this._anchor_32 = this.renderer.createTemplateAnchor(this._el_30,(null as any));
    this._appEl_32 = new import2.AppElement(32,30,this,this._anchor_32);
    this._TemplateRef_32_5 = new import23.TemplateRef_(this._appEl_32,viewFactory_ListMemberComponent5);
    this._NgFor_32_6 = new import33.NgFor(this._appEl_32.vcRef,this._TemplateRef_32_5,this.parentInjector.get(import34.IterableDiffers),this.parent.ref);
    this._text_33 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import33.NgFor) && (32 === requestNodeIndex))) { return this._NgFor_32_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.members;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_32_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.trackByFn;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_32_6.ngForTrackBy = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForTrackBy'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_32_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_32_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ListMemberComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ListMemberComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_ListMemberComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _RouterLinkWithHref_17_3:import20.RouterLinkWithHref;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _RouterLinkWithHref_20_3:import20.RouterLinkWithHref;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ListMemberComponent5,renderType_ListMemberComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._el_17 = this.renderer.createElement(this._el_16,'a',(null as any));
    this._RouterLinkWithHref_17_3 = new import20.RouterLinkWithHref(this.parent.parentInjector.get(import25.Router),this.parent.parentInjector.get(import26.ActivatedRoute),this.parent.parentInjector.get(import27.LocationStrategy));
    this._text_18 = this.renderer.createText(this._el_17,'Edit',(null as any));
    this._text_19 = this.renderer.createText(this._el_16,' | ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_16,'a',(null as any));
    this._RouterLinkWithHref_20_3 = new import20.RouterLinkWithHref(this.parent.parentInjector.get(import25.Router),this.parent.parentInjector.get(import26.ActivatedRoute),this.parent.parentInjector.get(import27.LocationStrategy));
    this._text_21 = this.renderer.createText(this._el_20,'View',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_17,'click',this.eventHandler(this._handle_click_17_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.RouterLinkWithHref) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._RouterLinkWithHref_17_3; }
    if (((token === import20.RouterLinkWithHref) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkWithHref_20_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_7:any = import4.interpolate(1,'/member/edit/',this.context.$implicit._id,'');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkWithHref_17_3.routerLink = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_17_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_10:any = import4.interpolate(1,'/member/view/',this.context.$implicit._id,'');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._RouterLinkWithHref_20_3.routerLink = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_20_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.context.$implicit.firstName;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'innerText',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.$implicit.lastName;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_4,'innerText',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.$implicit.memberId;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_6,'innerText',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.$implicit.mobile;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_8,'innerText',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.$implicit.email,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_11,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.context.$implicit.address,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_14,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._RouterLinkWithHref_17_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_17,'href',this.viewUtils.sanitizer.sanitize(import32.SecurityContext.URL,currVal_8));
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._RouterLinkWithHref_20_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_20,'href',this.viewUtils.sanitizer.sanitize(import32.SecurityContext.URL,currVal_11));
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_17_3.ngOnDestroy();
    this._RouterLinkWithHref_20_3.ngOnDestroy();
  }
  private _handle_click_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_17_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_20_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ListMemberComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ListMemberComponent5(viewUtils,parentInjector,declarationEl);
}