/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './view.member.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from './member.service';
import * as import11 from '../error/error.service';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../header/header.component';
import * as import15 from '@angular/common/src/directives/ng_if';
import * as import16 from '../header/header.component.ngfactory';
import * as import17 from '../auth/auth.service';
import * as import18 from '@angular/core/src/linker/template_ref';
var renderType_ViewMemberComponent_Host:import0.RenderComponentType = (null as any);
class _View_ViewMemberComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ViewMemberComponent_0_4:import3.ViewMemberComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ViewMemberComponent_Host0,renderType_ViewMemberComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-view-member',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ViewMemberComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ViewMemberComponent_0_4 = new import3.ViewMemberComponent(this.parentInjector.get(import8.Router),this.parentInjector.get(import9.ActivatedRoute),this.parentInjector.get(import10.MemberService),this.parentInjector.get(import11.ErrorService));
    this._appEl_0.initComponent(this._ViewMemberComponent_0_4,[],compView_0);
    compView_0.create(this._ViewMemberComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ViewMemberComponent) && (0 === requestNodeIndex))) { return this._ViewMemberComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ViewMemberComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._ViewMemberComponent_0_4.ngOnDestroy();
  }
}
function viewFactory_ViewMemberComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ViewMemberComponent_Host === (null as any))) { (renderType_ViewMemberComponent_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,[],{})); }
  return new _View_ViewMemberComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ViewMemberComponentNgFactory:import13.ComponentFactory<import3.ViewMemberComponent> = new import13.ComponentFactory<import3.ViewMemberComponent>('app-view-member',viewFactory_ViewMemberComponent_Host0,import3.ViewMemberComponent);
const styles_ViewMemberComponent:any[] = ['../app.component.css'];
var renderType_ViewMemberComponent:import0.RenderComponentType = (null as any);
class _View_ViewMemberComponent0 extends import1.AppView<import3.ViewMemberComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import14.HeaderComponent;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import15.NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _el_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  _el_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _el_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ViewMemberComponent0,renderType_ViewMemberComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'app-header',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import16.viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import14.HeaderComponent(this.parentInjector.get(import17.AuthService));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,[],(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_2 = new import2.AppElement(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import18.TemplateRef_(this._appEl_2,viewFactory_ViewMemberComponent1);
    this._NgIf_2_6 = new import15.NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_4 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','row');
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','col-md-8 col-md-offset-2');
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'h2',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Personal Details',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_6,'h4',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Member ID: ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'strong',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Name: ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'strong',(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'PAN NO: ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'strong',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'',(null as any));
    this._text_25 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'AADHAR NO: ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'strong',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Mobile: ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'strong',(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'',(null as any));
    this._text_35 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Email: ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'strong',(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'',(null as any));
    this._text_40 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Gender: ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'strong',(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'',(null as any));
    this._text_45 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'Date of Birth: ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'strong',(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'',(null as any));
    this._text_50 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'Residential Address: ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'strong',(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'',(null as any));
    this._text_55 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_6,'br',(null as any));
    this._el_57 = this.renderer.createElement(this._el_6,'hr',(null as any));
    this._el_58 = this.renderer.createElement(this._el_6,'br',(null as any));
    this._text_59 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_6,'h2',(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'Nominee Details',(null as any));
    this._text_62 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'Nominee\'s Name: ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_63,'strong',(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'',(null as any));
    this._text_67 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'Nominee\'s Age: ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_68,'strong',(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'',(null as any));
    this._text_72 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'Nominee\'s Relation: ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_73,'strong',(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'',(null as any));
    this._text_77 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_78 = this.renderer.createElement(this._el_6,'br',(null as any));
    this._el_79 = this.renderer.createElement(this._el_6,'hr',(null as any));
    this._el_80 = this.renderer.createElement(this._el_6,'br',(null as any));
    this._text_81 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_6,'h2',(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'Employment or Business Details',(null as any));
    this._text_84 = this.renderer.createText(this._el_6,'\n\n        ',(null as any));
    this._el_85 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'Company: ',(null as any));
    this._el_87 = this.renderer.createElement(this._el_85,'strong',(null as any));
    this._text_88 = this.renderer.createText(this._el_87,'',(null as any));
    this._text_89 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_90 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_91 = this.renderer.createText(this._el_90,'Designation: ',(null as any));
    this._el_92 = this.renderer.createElement(this._el_90,'strong',(null as any));
    this._text_93 = this.renderer.createText(this._el_92,'',(null as any));
    this._text_94 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_95 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'Department: ',(null as any));
    this._el_97 = this.renderer.createElement(this._el_95,'strong',(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'',(null as any));
    this._text_99 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_6,'p',(null as any));
    this._text_101 = this.renderer.createText(this._el_100,'Office Address: ',(null as any));
    this._el_102 = this.renderer.createElement(this._el_100,'strong',(null as any));
    this._text_103 = this.renderer.createText(this._el_102,'',(null as any));
    this._text_104 = this.renderer.createText(this._el_6,'\n\n    ',(null as any));
    this._text_105 = this.renderer.createText(this._el_4,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._el_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._el_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._text_104,
      this._text_105
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    if (((token === import18.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import15.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeaderComponent_0_4.ngOnInit(); }
    const currVal_0:any = this.context.loading;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_2_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import4.interpolate(1,'',this.context.memberId,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_14,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(3,'',this.context.firstName,' ',this.context.middleName,' ',this.context.lastName,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_19,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.panNo,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_24,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.aadharNo,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_29,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.context.mobile,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_34,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.context.email,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_39,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'',this.context.gender,'');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_44,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,'',this.context.dob,'');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_49,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = import4.interpolate(1,'',this.context.address,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_54,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = import4.interpolate(3,'',this.context.nomineeFirstName,' ',this.context.nomineeMiddleName,' ',this.context.nomineeLastName,'');
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_66,currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = import4.interpolate(1,'',this.context.nomineeAge,'');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_71,currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = import4.interpolate(1,'',this.context.nomineeRelation,'');
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_76,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = import4.interpolate(1,'',this.context.company,'');
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setText(this._text_88,currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = import4.interpolate(1,'',this.context.designation,'');
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_93,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = import4.interpolate(1,'',this.context.department,'');
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_98,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = import4.interpolate(1,'',this.context.officeAddress,'');
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_103,currVal_16);
      this._expr_16 = currVal_16;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ViewMemberComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ViewMemberComponent> {
  if ((renderType_ViewMemberComponent === (null as any))) { (renderType_ViewMemberComponent = viewUtils.createRenderComponentType('/Users/prasadsawant/Sites/fintech_mean/frontend/app/member/view.member.component.html',0,import12.ViewEncapsulation.Emulated,styles_ViewMemberComponent,{})); }
  return new _View_ViewMemberComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ViewMemberComponent1 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ViewMemberComponent1,renderType_ViewMemberComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','loading');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_ViewMemberComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ViewMemberComponent1(viewUtils,parentInjector,declarationEl);
}